### PR TITLE
Use GitHub Actions matrix feature to build and release

### PR DESCRIPTION
**Pull request by U-v-U**
## All CI execution time reduced to 3 minutes

- Removed `s390x`, `ppc64` and `ppc64le` ~~by the way~~
- Removed the `MIPS SoftFloat` ~~by the way~~
- Transfer from `v2fly/V2FlyBleedingEdgeBinary` to GitHub Actions Artifact
   - See https://github.com/v2fly/v2ray-core/actions/runs/388904443 (requires GitHub account to download)
- Rewrite the signature script **a little bit**: https://github.com/v2fly/v2ray-core/commit/afdd5ac3fade0bf3a287eba4e9f4e45ce869950c Not tested (it theoretically works)
- Migrate from Bazel to `go build` compilation (~~Okay, Bazel can be removed~~

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
You can check my build results out here:

https://github.com/Loyalsoldier/v2ray-core/actions/runs/389419962
https://github.com/Loyalsoldier/v2ray-core/releases/tag/v4.33.5

**Comment by U-v-U** [comment]
LGTM, Do we need to test the release process?

**Comment by Loyalsoldier** [comment]
> LGTM, Do we need to test the release process?

Not necessary. BTW, what about reproducible build?

**Comment by U-v-U** [comment]
Those binaries are built via `go build ...` which is exactly what Bazel was doing (previously)
This should not be a problem.

I'm not familiar with the verification prodeture of a reproducible build. I'm hoping someone could help me verifying it.

**Review by Loyalsoldier — APPROVED** [review]

**Pull request merged**
