### PR TITLE
go style commands, merge v2ctl commands, v5 oriented

### PR DESCRIPTION
**Pull request by qjebbs**
This PR introduces `go` style commands for v2ray v5.

```
A unified platform for anti-censorship.

Usage:

        v2ray <command> [arguments]

The commands are:

        run          Run V2Ray with config
        api          Call V2Ray API
        convert      Convert multiple json config to protobuf
        tls          TLS tools
        uuid         Generate new UUIDs
        verify       Verify if a binary is officially signed
        version      Print V2Ray Versions

Use "v2ray help <command>" for more information about a command.
```

### CODE REVIEW

**Comment by qjebbs** [comment]
Now that sub commands are supported, `v2ray api` command is better to split to `v2ray api stat`,`v2ray api logger`,`v2ray api outbounds`,`v2ray api inbounds`,`v2ray api route`...

But this is not the objective of the PR, hope some one else will do it.

**Comment by kslr** [comment]
sorry, I did not notice this PR

**Comment by rprx** [comment]
Suggestion for Commands and Descriptions https://github.com/v2fly/v2ray-core/pull/335#issuecomment-717910249

**Comment by qjebbs** [comment]
The last commit restore the proto package to `github.com/golang/protobuf/proto`, though it is deprecated.

golang.org version of proto has removed UnmarshalText, without alternative. So it's unable to parse texts like `'name: "inbound>>>statin>>>traffic>>>downlink" reset: false'`. It's changes the way how api command works.

> User feel frustrated to write `'pattern: "" reset: false'`, even if new proto package supports to parse them

To switch to new proto package, we have to refactor api commands, to not use the handwriting request message, like:

```
v2ray api restartlog
v2ray api getstats "inbound>>>statin>>>traffic>>>downlink"
v2ray api getsysstats
v2ray api querystats -r -pattern=""
v2ray api addoutbounds c1.json c2.json ...
v2ray api addinbounds c1.json c2.json ...
v2ray api removeoutbounds c1.json tag ...
v2ray api removeinbounds  c1.json tag ...
```

But it's another story.

**Comment by kslr** [comment]
please add ``` test ``` command

**Comment by qjebbs** [comment]
BTW:

`v2ray run -test ...` is removed.

BUT,  while `v2ray test ...` is now only for files clearly specified, the last commit lower down the test ability, in some cases like:

- No equivalent to `v2ray run -test`, test for stdin input
- No equivalent to `v2ray run -test` + ENV DIR, test for files specified by ENV

## Solutions?
1. Make `v2ray test` waits and accepts from stdin, and respect ENV setting? It's weird for the command to test something not clearly specified
2. Keep both `v2ray test ...` and `v2ray -test ...`?
3. No change will be applied to this part?

**Comment by kslr** [comment]
>  ENV DIR, test for files specified by ENV

what does this mean?

**Comment by qjebbs** [comment]
> > ENV DIR, test for files specified by ENV
> 
> what does this mean?

`-test` works for config dir specified by ENV variable:

https://github.com/v2fly/v2ray-core/blob/9bf09b2242e564bf9ecadd3812e8342d5f2a4282/main/main.go#L73-L76

**Comment by kslr** [comment]
I think explicit parameters are more appropriate, What do you think?

**Comment by qjebbs** [comment]
> I think explicit parameters are more appropriate(no stdin, no env), What do you think?

Agree. Turning back one day later, I think the question here https://github.com/v2fly/v2ray-core/pull/369#issuecomment-728741078 is not a problem at all. User can test files explicitly, for which they formerly put into stdin, or in EVN folder.

**Comment by qjebbs** [comment]
> > > I think explicit parameters are more appropriate(no stdin, no env), What do you think?
> > 
> > 
> > Agree. Turning back one day later, I think the question here [#369 (comment)](https://github.com/v2fly/v2ray-core/pull/369#issuecomment-728741078) is not a problem at all. User can test files explicitly, for which they formerly put into stdin, or in EVN folder.
> 
> Now, Are you ready to merge

I guess so, finally ✌️

**Comment by kslr** [comment]
> > > > I think explicit parameters are more appropriate(no stdin, no env), What do you think?
> > > 
> > > 
> > > Agree. Turning back one day later, I think the question here [#369 (comment)](https://github.com/v2fly/v2ray-core/pull/369#issuecomment-728741078) is not a problem at all. User can test files explicitly, for which they formerly put into stdin, or in EVN folder.
> > 
> > 
> > Now, Are you ready to merge
> 
> I guess so, finally v

OK, Need Solve this conflicts first

**Review by kslr — APPROVED** [review]

**Review by xiaokangwang — APPROVED** [review]
Great work. No issue were discovered. I wonder why you didn't use the register command pattern?

**Comment by qjebbs** [comment]
@xiaokangwang  In most cases, the commands list is certain, it's better to leave the change to developer to decide the order (Though developers can still sort their sub commands in alphabetical order). Like:

```
v2ray api provides tools to manipulate V2Ray via its API.

Usage:

        v2ray api <command> [arguments]

The commands are:

        restartlogger Restart the logger
        stats         Get statistics
        statsquery    Query statistics
        statssys      Get system statistics
        adi           Add inbounds
        ado           Add outbounds
        rmi           Remove inbounds
        rmo           Remove outbounds

Use "v2ray help api <command>" for more information about a command.
```

To support cropping feature (the list is uncertain), we have to register commands in `init()`, this is the only reason why `RegisterCommand()` is added, and it comes with `SortCommands()`. But I think we can limit the cropping to first level commands, like `api`, `tls`...

**Comment by kslr** [comment]
```
  ~ v2ray run -c 1.json
V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64)
A unified platform for anti-censorship.
panic: open 1.json: no such file or directory

goroutine 1 [running]:
v2ray.com/core/common.Must(...)
        v2ray.com/core/common/common.go:26
v2ray.com/core/main/jsonem.init.0.func1(0xd2ce40, 0xc00025f6c0, 0x7ffc56e0d2e6, 0x4, 0xc000196160)
        v2ray.com/core/main/jsonem/jsonem.go:25 +0x44d
v2ray.com/core.LoadConfig(0xe8480f, 0x4, 0x7ffc56e0d2e4, 0x6, 0xd2ce40, 0xc00025f6c0, 0xc0001dbd58, 0x775f06, 0xf9f960)
        v2ray.com/core/config.go:66 +0x262
v2ray.com/core/main/commands.startV2Ray(0x10, 0x10, 0x7f1b01b54108, 0xc000229570)
        v2ray.com/core/main/commands/run.go:160 +0x12e
v2ray.com/core/main/commands.executeRun(0x14dd1a0, 0xc0000320b0, 0x0, 0x0)
        v2ray.com/core/main/commands/run.go:72 +0x4a
v2ray.com/core/commands/base.Execute()
        v2ray.com/core/commands/base/execute.go:64 +0x269
main.main()
        v2ray.com/core/main/main.go:16 +0x14a
```

Also, should we support ```  v2ray -c 1.json  ```?

**Comment by Loyalsoldier** [comment]
> ```
>   ~ v2ray run -c 1.json
> V2Ray 4.33.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.5 linux/amd64)
> A unified platform for anti-censorship.
> panic: open 1.json: no such file or directory
> 
> goroutine 1 [running]:
> v2ray.com/core/common.Must(...)
>         v2ray.com/core/common/common.go:26
> v2ray.com/core/main/jsonem.init.0.func1(0xd2ce40, 0xc00025f6c0, 0x7ffc56e0d2e6, 0x4, 0xc000196160)
>         v2ray.com/core/main/jsonem/jsonem.go:25 +0x44d
> v2ray.com/core.LoadConfig(0xe8480f, 0x4, 0x7ffc56e0d2e4, 0x6, 0xd2ce40, 0xc00025f6c0, 0xc0001dbd58, 0x775f06, 0xf9f960)
>         v2ray.com/core/config.go:66 +0x262
> v2ray.com/core/main/commands.startV2Ray(0x10, 0x10, 0x7f1b01b54108, 0xc000229570)
>         v2ray.com/core/main/commands/run.go:160 +0x12e
> v2ray.com/core/main/commands.executeRun(0x14dd1a0, 0xc0000320b0, 0x0, 0x0)
>         v2ray.com/core/main/commands/run.go:72 +0x4a
> v2ray.com/core/commands/base.Execute()
>         v2ray.com/core/commands/base/execute.go:64 +0x269
> main.main()
>         v2ray.com/core/main/main.go:16 +0x14a
> ```

As of config files that don't exist, I think it will be better just to warn it or print out errors other than panic.

**Comment by qjebbs** [comment]
@Loyalsoldier It's `jsonem` who panic the process, not the commands codes. 

https://github.com/v2fly/v2ray-core/blob/bb74ef99e2658a1690ed4ba62b370082f7779eb2/main/jsonem/jsonem.go#L24-L25

@kslr Compatible for `v2ray -c ...` is what we have discussed at the very beginning, but it's not elegant. Now that we are move on to v5,  it could be done (#370), but is better to remove this behavior.

See also: #335

**Review by qjebbs — COMMENTED** [review]
The last commit `fix default loader logic` https://github.com/v2fly/v2ray-core/pull/369/commits/906452cc4f724e0e13346308c12d630be2c32b00 fixes an issue former existed:

with the command line below
```
v2ray run -format=pb -c c.json
```

The former logic will load file with `json` loader, but when it's explicitly specified, user need `protobuf` loader, no matter the file has `json` or any other extension, for any reason.

Another scenario, which make this problem more significant:

- Suppose we have 2 loaders for json extension files in futuer, e.g. `json2`,
- With `v2ray run -format=json2 -c c.json`, the former logic will still use `json` instead of `json2`

**Comment by kslr** [comment]
you're right.

**Comment by rprx** [comment]
目前是否支持 `v2ray -c config.josn`？（即 run 为默认 command）

我觉得是否支持均可，但没有技术障碍的情况下，减少迁移成本比较合适。

**Comment by kslr** [comment]
抱歉，使用中文可以描述的更清楚。

我不赞成 run 成为默认命令 ，除非这可以简单的做到（一个语法糖）
-c 的话周边基础设施的确是遇到了一些麻烦，如果能同时支持并再逐渐迁移是最好的了，当然这个事情也可以放到这个 pr 之外。

**Review by rprx — APPROVED** [review]

**Comment by kslr** [comment]
thank you for your work, this is great

**Pull request merged**
