### PR TITLE
Add concurrent option for dns server

### PR DESCRIPTION
**Pull request by nekohasekai**
Allows concurrent lookup on the next server when this option is enabled, useful for scenarios where the primary DNS server is expected to fail (e.g. companies)

### CODE REVIEW

**Comment by database64128** [comment]
It's not V2Ray's job to workaround buggy DNS servers. Buggy DNS usually causes problems for the whole system, and I've never heard any system resolver that queries multiple DNS servers concurrently for this reason. I don't think this is the right way to deal with broken DNS servers. The user should just change or fix their DNS servers.

**Comment by nekohasekai** [comment]
> Users should

But it takes more effort for users to manually switch DNS servers each time or to avoid this problem than if we add this innocuous feature.

**Comment by database64128** [comment]
> But it takes more effort for users to manually switch DNS servers each time

I don't understand. Why would the user have to switch "every time"? Just don't use the broken server.

> this innocuous feature

More like an anti-pattern.

**Comment by nekohasekai** [comment]
> Why would the user have to switch "every time"

Because the environment is blocking other DNS services

**Comment by database64128** [comment]
> Because the environment is blocking other DNS services

This doesn't make any sense. The whole point of using V2Ray is to circumvent these restrictions.

**Comment by wloot** [comment]
> It's not V2Ray's job to workaround buggy DNS servers. Buggy DNS usually causes problems for the whole system, and I've never heard any system resolver that queries multiple DNS servers concurrently for this reason. I don't think this is the right way to deal with broken DNS servers. The user should just change or fix their DNS servers.

haproxy一直做的就是同时请求所有设置的dns服务器,并返回最快响应的ip。

**Comment by wloot** [comment]
> > Because the environment is blocking other DNS services
> 
> This doesn't make any sense. The whole point of using V2Ray is to circumvent these restrictions.

dns服务器失效可能在任何环境都存在，包括布置v2ray服务端的无审查服务器，这就是为什么允许存在多个后备dns服务器。而并发请求就是更积极应对这一情况的方案

**Pull request closed without merging**
