### PR TITLE
Restore the sysvinit service script.

### PR DESCRIPTION
**Pull request by pthfdr-42**
Not every distro use systemd due to the controversial nature of it.
You should keep this file for compatibility.

### CODE REVIEW

**Comment by kslr** [comment]
The cost of maintaining compatibility is too high.

**Comment by pthfdr-42** [comment]
Except it is not. In fact you can just left the script here as is.
There is really no major changes in init scripts in recent years, sans the executable path.

**Comment by database64128** [comment]
I don't think SysVinit should be supported.

I took a look at your past contributions. It seems you have done this kind of controversial/meaningless stuff before, like openssl/openssl#13744. I believe this PR should be closed.

**Comment by xiaokangwang** [comment]
I think sysvinit service can be kept if there is someone willing to maintain it.  

However, I cannot take this role since I have no idea how to write this.

**Pull request closed without merging**
