### PR TITLE
Merge v2ctl functionalities to v2ray

### PR DESCRIPTION
**Pull request by qjebbs**
This PR implements what we were discussing at https://github.com/v2fly/v2ray-core/issues/247#issuecomment-711707156:

1. imports `jsonem` and `yamlem` packages by default, to make v2ray load text-based configs without dependency
1. merge all v2ctl commands into v2ray, with cropping support, of course

    image

So, we got all v2ctl's functionalities, with no pain:

1. The publish size of v2ray doesn't grow
1. The cropped size of v2ray is still small

One more thing, this PR also improved the command usage infomation. 

`v2ray -h`:

```
Usage:

v2ray <command>
Available commands:
    api                          Call V2Ray API
    cert                         Generate TLS certificates.
    config                       Merge multiple json config
    fetch                        Fetch resources
    tlsping                      Ping the domain with TLS handshake
    uuid                         Generate new UUIDs
    verify                       Verify if a binary is officially signed.

Use "v2ray <command> -h" for more information.

Usage of v2ray:
  -c value
        Short alias of -config
  -confdir string
        A dir with multiple json config
  -config value
        Config file for V2Ray. Multiple assign is accepted (only json). Latter ones overrides the former ones.
  -format string
        Format of input file. (default "json")
  -test
        Test config file only, without launching V2Ray server.
  -version
        Show current version of V2Ray.
```

`v2ray api -h `:

```
Usage of api:
  -server string
        Server address (default "127.0.0.1:8080")
v2ray api [--server=127.0.0.1:8080] Service.Method Request
Call an API in an V2Ray process.
The following methods are currently supported:
        LoggerService.RestartLogger
        StatsService.GetStats
        StatsService.QueryStats
API calls in this command have a timeout to the server of 3 seconds.
Examples:
v2ray api --server=127.0.0.1:8080 LoggerService.RestartLogger '' 
v2ray api --server=127.0.0.1:8080 StatsService.QueryStats 'pattern: "" reset: false'
v2ray api --server=127.0.0.1:8080 StatsService.GetStats 'name: "inbound>>>statin>>>traffic>>>downlink" reset: false'
v2ray api --server=127.0.0.1:8080 StatsService.GetSysStats ''
```

PS: v2ctl works exactly the same to past.

### CODE REVIEW

**Comment by rprx** [comment]
非常支持此项更改，为了防止混淆，可以把 command config 改成 convert，支持 yaml 转 json、json 转 pb、yaml 转 pb

**Comment by rprx** [comment]
另外，应当加一个新的 command `run`，作为 v2ray 现有参数的 command，同时 `run` 可被省略，是 command 的缺省值

**Comment by kslr** [comment]
config 做成 convert 就很奇怪吧 不是有 --format 吗

**Comment by rprx** [comment]
> 
> 
> config 做成 convert 就很奇怪吧 不是有 --format 吗

指 v2ctl 的 config，它的功能就是 convert，不改名容易与 v2ray 的 -config 混淆（比如你已经混淆了。。。

https://www.v2fly.org/guide/command.html#v2ctl

**Comment by qjebbs** [comment]
run command has been implemented.

`v2ray help`:

```
v2ray <command>
Available commands:
    api                  Call V2Ray API
    cert                 Generate TLS certificates.
    config               Merge multiple json config
    fetch                Fetch resources
    help                 Show help
    run                  run v2ray, the default command
    tlsping              Ping the domain with TLS handshake
    uuid                 Generate new UUIDs
    verify               Verify if a binary is officially signed.

Use "v2ray help <command>" for more information.
```

`v2ray help` (cropped):

```
v2ray <command>
Available commands:
    help                 Show help
    run                  run v2ray, the default command

Use "v2ray help <command>" for more information.
```

`v2ray -h`:

```
Usage of run:
  -c value
        Short alias of -config
  -confdir string
        A dir with multiple json config
  -config value
        Config file for V2Ray. Multiple assign is accepted (only json). Latter ones overrides the former ones.
  -format string
        Format of input file. (default "json")
  -test
        Test config file only, without launching V2Ray server.
  -version
        Show current version of V2Ray.

'run' is the default command, the two command lines below are equivalent:

  main run -c config.json
  main -c config.json

More examples:

  main -c config.json -c c1.json -c <url>.json -confdir <dir>
  main -test <config>
  main -version

For all available commands, run 'main help'
```

**Comment by qjebbs** [comment]
Merged? Should I create another PR for the run command?😅

**Comment by qjebbs** [comment]
My intentions (functionalities merging) has been all implemented, till the latest commit. In case the PR is getting to large, we should stop here, for now.

Further works could be done with later commits or PRs(after discusstions):
- the config command stuff above mentioned
- merge more command, for both v2ray & v2ctl, like vmessping, etc.

**Comment by rprx** [comment]
辛苦了，我还没看代码，但这个 PR 的目标可以先被 merge，同时编译流程等其它地方可能也许要进行修改

关于指令的改名/合并/功能调整，我们可以在这个 PR 下讨论，然后开另一个 PR 来实现

**Comment by rprx** [comment]
比如原本关于 tls 的 command `cert`、`tlsping` 可以合并为 tls `cert`、`ping`

**Comment by rprx** [comment]
十分抱歉，目前关于是否/何时合并 v2ray 和 v2ctl 的讨论未达成一致，初步做法可能是先让 v2ray 不依赖 v2ctl，这个 PR 要再等等

**Comment by xiaokangwang** [comment]
Sorry, after a intense discussion in developer community, we believe merging the v2ctl into v2ray isn't aligned with our current roadmap, and will generate too much breaking changes. The original reason we decide to put it in a separate file is to reduce the binary size of v2ray and its memory requirements, which have not changed.

We advice you to request preapproval for any PR first before implementing it if the purpose of change is to merge into the main repo.

**Comment by rprx** [comment]
纠正：不是 breaking change 的问题（因为大多无感知），而是 v2ctl 可去可留，但尚未就未来架构达成共识

**Comment by qjebbs** [comment]
I understand and it's OK. 😄

The initial motivation of these is for my personal usage, actually I have planned more commands for myself, though I just send some of them for the PR.

If you guys don't mind, I'm closing the PR now.

BTW: There's no breaking change, all changes are compatible.

**Comment by kslr** [comment]
对于当下来说，不会选择合并 ctl 里的命令，但如果添加新的命令，会向core处理。
现在我们需要先剥离 core 和 ctl 之间的连接

**Comment by rprx** [comment]
此 PR 不必关闭，我个人始终支持此项更改，并且同样希望 v2ray 有更多 commands，同时保持简单的可裁剪性，比如 tag 编译

这应当是正确的发展方向，可以使 v2ray 更强大、更广泛应用，被更多的人所了解

**Comment by U-v-U** [comment]
我认为非必要功能不需要加在 core 内

**Comment by rprx** [comment]
> 
> 
> 我认为非必要功能不需要加在 core 内

严格来说，每项功能是否必要取决于使用者，我们给出预设分割不会带来足够的好处

**Comment by qjebbs** [comment]
@kslr Are you suggesting that do not introduce package ʻinfra/control/commands`? (the PR provides kind of facility for new commands, though it's debatable)
@U-v-U Are you suggesting that splits package ʻinfra/control/commands` to essential and non-essential ones?
@rprx I agree
Anyway, this PR will keep freeze until you guys have new resolution.

**Comment by qjebbs** [comment]
To report my use case for discussion and explain what "the initial motivation" mentioned above is, I want to show changes of my [personal fork](https://github.com/qjebbs/v2ray-core) until now:

- It's forked from v4.36.0, since many nodes of my service provider still not work with v4.28.1 or later
- api command now has the capbility add/remove outbounds (HandlerService)
- Added commands: 

        merge                Merge json files into one
        subs                 Fetch subscriptions and save to json
        vmessping            Ping through an outbound from a vmess link or json file

My use case is:

1. `v2ray merge ...` for self-contained config files, which are easier to manage
2. `v2ray subs ...` to download & update service subscriptions
3. `v2ray vmessping ...` is scheduled to check availabity of server nodes
4. `v2ray api HandlerService...` to add/remove nodes accrording to check result

Why I want to merge functionalities?

- While `vmessping` and `v2ray` are seprated distributions, they can depend on different versions of code.
- Suppose `vmessping:1.24.0`,`v2ray:1.32.0`
- According to my use case steps 3-4, we know that, a good node for `vmessping`, could have chance not work with `v2ray`

But if `vmessping` is inside `v2ray`, we are sure good check leads to good work.

**Comment by qjebbs** [comment]
One more thing, cropping (force to us `pb`) is not an option for my use case, since we need to convert vmess link to JSON, and load it. So I need ctl functionalities definitely, merge them saves me half of the space in the router.

A separated `v2ctl`'s use case is really rare:

- User has a router out of time, which with really small storage
- But the out-dated router happens  to support floating number instruction
- He/She shouldn't has complex needs, like subscriptions
- He/She can bear with a complicated flow to update any configs: Editing text-json, conver to pb in anther terminal, upload it...

**Comment by rprx** [comment]
（当务之急是先解除 v2ray 对 v2ctl 的依赖，欢迎 PR）

**Comment by qjebbs** [comment]
@rprx https://github.com/v2fly/v2ray-core/pull/299

**Comment by rprx** [comment]
> 
> 
> @rprx #299

这个 PR 不能读取多文件配置，还需要些相关修改。

**Comment by qjebbs** [comment]
@rprx What do you mean by `这个 PR 不能读取多文件配置`?

https://github.com/v2fly/v2ray-core/blob/c325faef380e8643926cae0d1c343a00f86acfc5/main/jsonem/jsonem.go#L22-L29

I see `jsonem` here reads multiple json, and overrides as described in document.

**Comment by xiaokangwang** [comment]
> （当务之急是先解除 v2ray 对 v2ctl 的依赖，欢迎 PR）

This is not what we have agreed on meeting. The change we have purposed can be done easily without the need of PR, since that only need uncomment one line of code. You should not pre-approve PR on things that do not need a PR.

**Comment by forever8938** [comment]
@rprx @qjebbs Sorry, I tested again and [multiple config feature](https://www.v2fly.org/config/multiple_config.html) does work when #299 is applied. Now it should be fine to merge it.

**Comment by rprx** [comment]
> 
> 
> > （当务之急是先解除 v2ray 对 v2ctl 的依赖，欢迎 PR）
> 
> This is not what we have agreed on meeting. The change we have purposed can be done easily without the need of PR, since that only need uncomment one line of code. You should not pre-approve PR on things that do not need a PR.

需要说明，共识的确是先解除 v2ray 对 v2ctl 的依赖，@forever8938 提交 #299 时自己说了只能读取单个文件，导致我以为需要更多修改，于是鼓励 PR。同时回复 @qjebbs

**Comment by rprx** [comment]
https://github.com/v2fly/v2ray-core/issues/360

**Comment by rprx** [comment]
### 整体方案如下

v2ray 的 commands，增加 `run` 作为默认 command，去掉 `fetch`（这个的确没必要）
```
run
api
uuid
verify
convert，原 config，需要加功能
tlscert，原 cert
tlsping
lovevictoria，彩蛋
```
输出版本只有 `v2ray -v/version`，不含 `run`；帮助用 `-h/help` 表示，`v2ray -h` 不同于 `v2ray run -h`

bazel 需要调整为只编译 v2ray 二进制，类 unix 的生成一个 v2ray 的 v2ctl 软链，zip -y

v2ray 和 v2ctl 合并后可以重新引入 yaml 支持，不存在 #331 提到的交互问题了

目测 v2ray 的体积不会有明显变化，v2ctl 暂时仍可以被手动编译出来，之后再逐步向 tag 裁剪过渡

（关于 -v，也可以同时支持 -V，但如果只支持 -v，使用者会记得更牢）

**Comment by rprx** [comment]
如果这项改变出现在 v5 中，就一步到位完全删掉 v2ctl，不做软链，不留供编译的代码

**Comment by qjebbs** [comment]
@rprx 确实是，还是你们看得仔细：

- 现有 v2ray -h 等同于 v2ray run -h 是有点不符合直觉。v2ray -h 应该等于 v2ray help。
- v2ray run -v 也很别扭

但目前有个问题，v2ray -v / v2ray -version` 单独拿出来处理时，我可以让 `v2ray -h`时默认的那一堆默认帮助不打印，但总还是要显示点提示的（下方2号标记）。

```
v2ray <command>
Available commands:
    api          Call V2Ray API
    convert      Convert multiple json config to protobuf
    help         Show help
    run          run v2ray, the default command
    tlscert      Generate TLS certificates.
    tlsping      Ping the domain with TLS handshake
    uuid         Generate new UUIDs
    verify       Verify if a binary is officially signed.
    version      print V2Ray version （1）

Use "v2ray -v" or "v2ray -version" to print V2Ray version. （2）

Use "v2ray help <command>" for more information.
```

现在变成 1和2号标记二选一的问题，我觉得还是加个version命令，只显示1更简洁舒服（go 的命令行就是这样做的）：用户来看帮助时，都被引导去 `v2ray vesion`命令，`v2ray -v` 作为兼容措施，默默工作就行了。

先按以上思路提交commit，如果有问题我们再调整

**Comment by rprx** [comment]
（此处有误会，是 `v2ray -v/-version` 和 `v2ray -h/-help`，`version` 和 `help` 不是那些指令，属于特殊处理。）

不过如果按 go 的做法来，的确是只有 `go version` 和 `go help xxx`，似乎这样的形式更统一，我想一下。

**Comment by qjebbs** [comment]
在入口处的顶层解析参数，必然要求介绍这些参数，这就导致既写参数又写命令列表的局面。

目前提交的已经是我能想到的，最能兼顾兼容与用户体验的方案。当然不排除你有更好的方案。

实际上，无论是顶层解析还是默认命令，都是为了照顾兼容性。V5没有这些包袱，这块代码到时可以更简洁、更有一致性、在顶层不解析任何参数。即，不提供 `v2ray -h`和`v2ray -v`。go命令行就是这种状态，没有`go -h`。

还有一点，现在的整个方案，`-h`参数，既被偷偷地占用掉了（不显式介绍、但可用：与help等效），又不允许新命令的作者把 `-h` 另做他用。这一点，也是延续原有命令代码的惯性写下来的，在go那边也不存在的。

**Comment by rprx** [comment]
@qjebbs 

-h 不要了，无法解析就显示 help

**Comment by rprx** [comment]
决定采用下面的形式，若与前面的说法冲突，以此为准：

# v2ray commands

```
> v2ray

V2Ray is a platform for building proxies.

Usage:

    v2ray <command> [arguments]

The commands are:

    run              Run V2Ray with config, the default command
    api              Call an API in a V2Ray process
    build            Build a stand-alone V2Ray binary with config
    convert          Merge multiple json config
    test             Test config file only, without launching V2Ray
    tlscert          Generate TLS certificates
    tlsping          Ping the domain with TLS handshake
    uuid             Generate new UUIDs
    verify           Verify if a binary is officially signed
    version          Show current version of V2Ray

Use "v2ray help <command>" for more information about a command.
```

```
> v2ray help run

Run V2Ray with config, the default command, the two command lines below are equivalent:

    v2ray run -c config.json
    v2ray -c config.json

Arguments:

    -c value
        Short alias of -config

    -confdir string
        A dir with multiple json config

    -config value
        Config file for V2Ray. Multiple assign is accepted (only json). Latter ones overrides the former ones.

    -format string
        Format of input file. (default "json")
```

```
> v2ray help api

Call V2Ray API, API calls in this command have a timeout to the server of 3 seconds.

Usage:

    v2ray api --server=127.0.0.1:8080] Service.Method

The following methods are currently supported:

    LoggerService.RestartLogger
    StatsService.QueryStats
    StatsService.GetStats
    StatsService.GetSysStats

Examples:

    v2ray api --server=127.0.0.1:8080 LoggerService.RestartLogger ''
    v2ray api --server=127.0.0.1:8080 StatsService.QueryStats 'pattern: "" reset: false'
    v2ray api --server=127.0.0.1:8080 StatsService.GetStats 'name: "inbound>>>statin>>>traffic>>>downlink" reset: false'
    v2ray api --server=127.0.0.1:8080 StatsService.GetSysStats ''
```

```
> v2ray help build

Build a stand-alone V2Ray binary with config, maybe possible.

Usage:

    ...
```

```
> v2ray help convert

Merge multiple json config.

Usage:

    v2ray convert config.json c1.json c2.json <url>.json

Arguments:

    ...
```

```
> v2ray help test

Test config file only, without launching V2Ray.

Usage:

    ...

Arguments:

    ...
```

```
> v2ray help tlscert

Generate TLS certificates.

Usage:

    v2ray tlscert [--ca] [--domain=v2fly.org] [--expire=240h]

Arguments:

    --ca
        The new certificate is a CA certificate.

    --domain
        Common name for the certificate.

    --expire
        Time until certificate expires. 240h = 10 days.
```

```
> v2ray help tlsping

Ping the domain with TLS handshake.

Usage:

    v2ray tlsping <domain> --ip <ip>

Arguments:

    ...
```

```
> v2ray help uuid

Generate new UUIDs.

Usage:

    v2ray uuid
```

```
> v2ray help verify

Verify if a binary is officially signed.

Usage:

    v2ray verify [--sig=/path/to/sigfile] <filepath>

Arguments:

    ...
```

```
> v2ray help version

Show current version of V2Ray.

Usage:

    v2ray version
```

**Comment by rprx** [comment]
关于 `v2ray` 的行为兼容处理：

额外支持 `-test` 和 `-version`，若出现了 `run` 的 arguments 则按 `run` 处理。

其它情况，command 不对时一律显示 help，包括仅 `v2ray`。若 command 正确但缺少必要参数，则显示对应 command 的 help。

还会逐步补充内容。

**Comment by rprx** [comment]
`v2ray build` 暂时不用考虑，`v2ray lovevictoria` 彩蛋保留。

现在放到 v5，可以选择 breaking，仅 `v2ray` 这里就是，但 `v2ray run` 可以是现在 `v2ray` 的行为。

**Comment by kslr** [comment]
> v2ray

如果按照 go 风格第一个空行也不保留；
V2Ray is a platform for building proxies. -> A unified platform for anti-censorship 更酷一点

最后别忘记了 lint fix

**Comment by rprx** [comment]
@kslr 

空行是没有的，上面是为了显示清晰。简述是随便写的示例，可以修改，不过我觉得我们最好把 v2ray 定位为一个更通用的代理工具？

**Comment by qjebbs** [comment]
#370

**Pull request closed without merging**
