### PR TITLE
remove old Shadowsocks implementation

### PR DESCRIPTION
**Pull request by kslr**
AES-256-CFB
    AES-128-CFB
    ChaCha20
    ChaCha20-IETF

ref https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.0.0

### CODE REVIEW

**Comment by kslr** [comment]
https://github.com/v2fly/V2FlyBleedingEdgeBinary/releases/tag/unstable-0e0c11b659d4230082a3fc28869a952325d470b5

**Comment by DuckSoft** [comment]
Hmm……do we need to remove chacha20-ietf?

**Review by DuckSoft — CHANGES_REQUESTED** [review]
I suggest we remove OTA & (email?) only, for the current step.

**Review by studentmain — COMMENTED** [review]
remove OTA (email, chacha20) only, we need more work before remove chacha20-ietf and aes-cfb.

**Comment by xiaokangwang** [comment]
If this kind of old codes is not currently interfering with any new things, I would like to keep them.

I rather not to break someone's setup without a reason.

**Comment by studentmain** [comment]
> If this kind of old codes is not currently interfering with any new things, I would like to keep them.
> 
> I rather not to break someone's setup without a reason.

https://github.com/shadowsocks/shadowsocks-org/issues/30 

one of the reason

**Pull request closed without merging**
