### PR TITLE
Add PATCH TRACE http method to sniffer

### PR DESCRIPTION
**Pull request by ayanamist**

### CODE REVIEW

**Review by AkinoKaede — APPROVED** [review]

**Comment by AkinoKaede** [comment]
Could you cherry-pick your commit to master branch and force push it?

**Comment by ayanamist** [comment]
Yes. Sorry i forget this thing after whole day work. I will rebase it tomorrow

**Comment by ayanamist** [comment]
Rebase done

**Comment by kslr** [comment]
Thanks for your work.

**Pull request merged**
