### PR TITLE
feat: v5 trojan complete config

### PR DESCRIPTION
**Pull request by mkmark**
v5 config currently only implements simplified proxies. This blocks advanced features based on missing properties.
This pull request proposes to implement full config for proxies.
trojan is implemented as demonstration.

### CODE REVIEW

**Comment by AkinoKaede** [comment]
Modifying the short name of an existing configuration type `trojan` is breaking change. A more benign choice might be to name the new configuration type`trojan_full`.

**Comment by mkmark** [comment]
> Modifying the short name of an existing configuration type `trojan` is breaking change. A more benign choice might be to name the new configuration type `trojan_full`.

Of course that could be managed! But it was intended.

To decide two formats, with exclusive functionality and simplicity, which has the right to inherit a more formal title (in this case, "trojan"), it was my belief that functionality wins, and its similarity to v4 config just adds to the rationality. It's quite a personal and subjective idea though. Also, the docs shows that the v5 config is still in sketch and subject to change, so I proposed this change.

It's rather a demonstration of concept for now, and there is no technical issues just to rename things from 'trojan' to 'trojan_full'.

I am willing to create a complete pull request to go through all the proxy config should you maintainers consider it preferable. If so, please also specify whether you'd like to rename "trojan" alike to "trojan_simple", or just add the new one with the "_full" suffix.

**Comment by xiaokangwang** [comment]
Hi! The full configuration format that would be necessary for advanced usage can be accessed with hash tag full name notation like `"protocol": "#v2ray.core.proxy.socks.ClientConfig",` as shown in https://github.com/v2fly/v2ray-core/pull/2933. It is automatically implemented and does not to be implemented again. Documentation pull request about this is welcomed. 

Is there anything you are intending to achieve cannot be achieved with this?

**Comment by mkmark** [comment]
Glad I asked here first... The docs definitely needs some update, I'll see what I can do.

**Pull request closed without merging**
