### PR TITLE
remove deprecate ciphers in shadowsocks

### PR DESCRIPTION
**Pull request by kslr**

### CODE REVIEW

**Comment by kslr** [comment]
TestQUICNameServer to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.

**Comment by Loyalsoldier** [comment]
Is it better to be merged into v5?

**Comment by kslr** [comment]
> Is it better to be merged into v5?

ss has been removed in the latest version https://github.com/shadowsocks/shadowsocks-windows/releases/tag/4.4.0.0

**Review by Loyalsoldier — APPROVED** [review]

**Comment by maskedeken** [comment]
> TestQUICNameServer to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
> 
> cc @maskedeken

sysctl -w net.core.rmem_max=2500000

**Comment by kslr** [comment]
> > TestQUICNameServer to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
> > cc @maskedeken
> 
> sysctl -w net.core.rmem_max=2500000

Should we state this in the guide?

**Comment by maskedeken** [comment]
> 
> 
> > > TestQUICNameServer to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
> > > cc @maskedeken
> > 
> > 
> > sysctl -w net.core.rmem_max=2500000
> 
> Should we state this in the guide?

这是quic-go的信息。如果不调整sysctl.conf，quic-go发起连接时也会通过setReadBuffer调大缓存大小，这个出错信息的出现，表示setReadBuffer最终也没有把缓存调整到期望的大小

**Pull request merged**
