### PR TITLE
Fix http outbound to get correct TLS negotiated protocol when "stats" setting exists

### PR DESCRIPTION
**Pull request by darhwa**
Sorry to open a new pull request, because I forgot to do some change in the old one (#73)

### CODE REVIEW

**Comment by yuhan6665** [comment]
Thanks a lot for fixing this issue!

**Comment by rprx** [comment]
Thank you for your work, but seems it's not necessary to delete line 135; 145-147; 169-171; 277-288, could you please do some adjustments? ("Fix http outbound" is OK

**Comment by darhwa** [comment]
@rprx 

The deleted lines are indeed safe to delete. And actually I'm the one who added the original code :)

The ctx within http.Request in L135 is never used in v2ray. And the original https://github.com/v2fly/v2ray-core/blob/cfbb875546e66d448409fbbebd3e9076f2b90c60/proxy/http/client.go (before my last patch) doesn't have it either.

L145-147 and L169-171 have no effect in a client request, according to https://github.com/golang/go/blob/2cd2ff6f564dce5be0c4fb7f06338ff7af3fc9a9/src/net/http/request.go#L128-L133

L277-288 are engaged also only at server side in golang's codebase, which is not the case of an "outbound".

**Comment by rprx** [comment]
@darhwa 

I see, and thanks again for your work.

**Pull request merged**
