### PR TITLE
Apply routing for non-local DoH requests

### PR DESCRIPTION
**Pull request by zinglau**
This regression was introduced in 04a0c0493449441020351bff47930c357618222a, and prevents routing rules from being applied to DoH server(s).

### CODE REVIEW

**Comment by xiaokangwang** [comment]
会不会出现规则需要DNS解析域名后才能判断，然后DNS解析域名又要走规则的问题？

**Comment by zinglau** [comment]
This patch needs further work and testing. In its current form, DOHL may get routed too.

> 会不会出现规则需要DNS解析域名后才能判断，然后DNS解析域名又要走规则的问题？

Yes.  But this is usually not a problem, because "dns" is individually tagged and therefore can be easily and explicitly assigned a definite route.

Ultimately, working (routed) DoH relies on proper configuration. For example, if only DoH server is defined in "dns", it will have to resolve itself, which creates an infinite loop and crashes the program. Some checking in code is necessary to prevent this.

**Comment by zinglau** [comment]
> This patch needs further work and testing. In its current form, DOHL may get routed too.

Tested. DOHL is not affected.

> 
> > 会不会出现规则需要DNS解析域名后才能判断，然后DNS解析域名又要走规则的问题？
> 
> Yes. But this is usually not a problem, because "dns" is individually tagged and therefore can be easily and explicitly assigned a definite route.

If the route uses outbound that uses domain to specify upstream and consequently depends on DNS query, it will indeed fail. But this is basically a problem of bad config.

> 
> Ultimately, working (routed) DoH relies on proper configuration. For example, if only DoH server is defined in "dns", it will have to resolve itself, which creates an infinite loop and crashes the program. Some checking in code is necessary to prevent this.

Check added in second patch.

**Comment by zinglau** [comment]
[dohtest.zip](https://github.com/v2fly/v2ray-core/files/4886298/dohtest.zip)

Simple config for testing.

**Comment by kslr** [comment]
It seems to destroy the existing configuration, we need to find a way

**Comment by Loyalsoldier** [comment]
Closed due to inactivity.

**Pull request closed without merging**
