### PR TITLE
Add HTTPUpgrade transport

### PR DESCRIPTION
**Pull request by xiaokangwang**
This is a reduced version of WebSocket transport that does not require actually implementing/using Websocket protocol itself. It sends http upgrade header to WebSocket and then use the upgraded http1.1 connection directly, cutting unnecessary overhead and protocol complexity of WebSocket.

This design is inspired by https://www.usenix.org/conference/foci20/presentation/frolov and based on [WebTunnel](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/webtunnel) Implementation.

Server Config Example, when hide behind nginx that deals with tls:
```
{
  "log": {
    "error": {
      "level": "Debug",
      "type": "Console"
    },
    "access": {
      "type": "None"
    }
  },
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ],
  "inbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "users": [
          "1234"
        ]
      },
      "listen": "127.0.0.1",
      "port": 1234,
      "streamSettings": {
        "transport": "httpupgrade",
        "transportSettings": {
          "host": "XXXX",
          "path": "XXXX"
        }
      }
    }
  ]
}
```

Client Config Example:
```
{
  "log": {
    "error": {
      "level": "Debug",
      "type": "Console"
    },
    "access": {
      "type": "None"
    }
  },
  "outbounds": [
    {
      "protocol": "vmess",
      "settings": {
        "port": 443,
        "uuid": "XXXX",
        "address": "XXXX"
      },
      "streamSettings": {
        "transport": "httpupgrade",
        "transportSettings": {
          "host": "XXXX",
          "path": "XXXX"
        },
        "security": "tls",
        "securitySettings": {
          "serverName": "XXXX",
          "allowInsecure": false,
          "nextProtocol": [
            "http/1.1"
          ]
        }
      }
    }
  ],
  "inbounds": [
    {
      "protocol": "socks",
      "settings": {
        "udpEnabled": true,
        "address": "127.0.0.1",
        "packetEncoding": "Packet"
      },
      "port": 1080
    }
  ]
}
```

### CODE REVIEW

**Comment by zirconpl** [comment]
Unable to use Nginx reverse proxy with HTTPUpgrade.
If I directly access the V2Ray server's port `1314` using the V2Ray client, I can successfully connect. However, as soon as I incorporate Nginx reverse proxy and use the V2Ray client to access port `80` on Nginx, I am unable to establish a successful connection

Client outbound:
```json
{
  "protocol": "vmess",
  "settings": {
	"port": 1314,
	"uuid": "f48fd3ae-0c24-433e-af3b-e87338b74705",
	"address": "xxxx"
  },
  "streamSettings": {
	"transport": "httpupgrade",
	"transportSettings": {
	  "host": "xxxx",
	  "path": "1"
	},
	"security": "none"
  }
}
```

Server inbound:
```json
{
  "listen": "0.0.0.0",
  "port": 1314,
  "protocol": "vmess",
  "settings": {
	"users": [
	  "f48fd3ae-0c24-433e-af3b-e87338b74705"
	]
  },
  "streamSettings": {
	"transport": "httpupgrade",
	"transportSettings": {
	  "path": "1"
	}
  }
}
```

Nginx config:
```
location /1 {
    proxy_pass http://127.0.0.1:1314;
}
```



v2ray client log:
```
2023/10/29 13:19:05 [Info] [2844697326] transport/internet/httpupgrade: creating connection to tcp:xx.xx.xx.xx:80
2023/10/29 13:19:05 [Info] [2844697326] transport/internet/httpupgrade: creating connection to tcp:xx.xx.xx.xx:80
2023/10/29 13:19:06 [Info] [2844697326] transport/internet/httpupgrade: creating connection to tcp:xx.xx.xx.xx:80
2023/10/29 13:19:06 [Info] [2844697326] transport/internet/httpupgrade: creating connection to tcp:xx.xx.xx.xx:80
2023/10/29 13:19:07 [Info] [2844697326] transport/internet/httpupgrade: creating connection to tcp:xx.xx.xx.xx:80
2023/10/29 13:19:08 [Warning] [2844697326] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [transport/internet/httpupgrade: failed to dial request to tcp:xx.xx.xx.xx:80 > transport/internet/httpupgrade: unrecognized reply] > common/retry: all retry attempts failed
2023/10/29 13:19:08 [Warning] [2844697326] proxy/http: failed to read response from google.com > io: read/write on closed pipe
2023/10/29 13:19:08 [Info] [2844697326] app/proxyman/inbound: connection ends > proxy/http: failed to read http request > EOF
2023/10/29 13:20:00 [Debug] app/log: Logger closing
```

nginx log：
```
2023/10/29 05:19:05 [error] 1764374#1764374: *1 upstream prematurely closed connection while reading response header from upstream, client: yy.yy.yy.yy, server: , request: "GET /1 HTTP/1.1", upstream: "http://127.0.0.1:1314/1", host: "xx.xx.xx.xx"
2023/10/29 05:19:05 [error] 1764374#1764374: *1 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: yy.yy.yy.yy, server: , request: "GET /1 HTTP/1.1", upstream: "http://127.0.0.1:1314/1", host: "xx.xx.xx.xx"
```

**Comment by freedmanop** [comment]
照你的写法不能用，可以说详细一点吗

**Comment by DDCHlsq** [comment]
实测能用，延迟比 gRPC 传输略高，比 ws 低，但是速度是 gRPC 的 3 倍（GIA线路，本地千兆测试），

**Comment by CrazyBoyFeng** [comment]
@freedmanop 我估计你是用 v4 的模式载入的配置文件。httpupgrade 目前只提供了 v5 格式的配置接入：
```
./v2ray run -c config.json -format jsonv5
```

**Comment by HappyLife-page** [comment]
> @freedmanop 我估计你是用 v4 的模式载入的配置文件。httpupgrade 目前只提供了 v5 格式的配置接入：
> 
> ```
> ./v2ray run -c config.json -format jsonv5
> ```

请问这个，配置路由不生效呢
我两个写法都不起作用，想限制大陆访问的
写法1：
  "outbounds": [
    {
      "tag": "direct",
      "protocol": "freedom"
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "routing": {
      "domainStrategy": "IPOnDemand",
      "strategy": "rules",
      "rules": [
        {
          "type": "field",
          "ip": [
            "geoip:private"
          ],
          "outboundTag": "block"
        },
        {
          "type": "field",
          "domain": [
            "geosite:cn"
          ],
          "outboundTag": "block"
        },
        {
          "type": "field",
          "ip": [
            "geoip:cn"
          ],
          "outboundTag": "block"
        }
      ]
  }

写法2：
  "outbounds": [
    {
      "protocol": "freedom"
    }
  ],
  "outboundDetour": [
    {
      "protocol": "blackhole",
      "tag": "blocked"
    }
  ],
  "routing": {
      "domainStrategy": "IPIfNonMatch",
      "rules": [
        {
          "domain": [
              "geosite:cn"
          ],
          "outboundTag": "blocked",
          "type": "field"
        },
        {
          "ip": [
                "geoip:cn"
            ],
            "outboundTag": "blocked",
            "type": "field"
        }
      ]
  }

**Pull request merged**
