### PR TITLE
separate uTP sniffer from bittorrent

### PR DESCRIPTION
**Pull request by AkinoKaede**

### CODE REVIEW

**Review by kslr — APPROVED** [review]

**Comment by database64128** [comment]
Separating uTP from bittorrent is like separating the http sniffer into http/1.0, http/1.1, and h2c sniffers. When someone enables the bittorrent sniffer, they mean to let v2ray sniff out traffic of both bittorrent and uTP protocols. It's kind of pointless to have a separate sniffer for uTP.

**Comment by AkinoKaede** [comment]
> Separating uTP from bittorrent is like separating the http sniffer into http/1.0, http/1.1, and h2c sniffers. When someone enables the bittorrent sniffer, they mean to let v2ray sniff out traffic of both bittorrent and uTP protocols. It's kind of pointless to have a separate sniffer for uTP.

Actually, almost no one does not use http and tls sniffers at the same time, but they are separate.

**Comment by database64128** [comment]
> Actually, almost no one does not use `http` and `tls` sniffers at the same time, but they are separate.

TLS is a generic secure transport, its payload does not have to be HTTP.

uTP was specifically designed for BitTorrent.

> Micro Transport Protocol or μTP (sometimes also uTP) is an open UDP-based variant of the BitTorrent peer-to-peer file sharing protocol intended to mitigate poor latency and other congestion control problems found in conventional BitTorrent over TCP, while providing reliable, ordered delivery.

**Comment by AkinoKaede** [comment]
> > Actually, almost no one does not use `http` and `tls` sniffers at the same time, but they are separate.
> 
> TLS is a generic secure transport, its payload does not have to be HTTP.
> 
> uTP was specifically designed for BitTorrent.
> 
> > Micro Transport Protocol or μTP (sometimes also uTP) is an open UDP-based variant of the BitTorrent peer-to-peer file sharing protocol intended to mitigate poor latency and other congestion control problems found in conventional BitTorrent over TCP, while providing reliable, ordered delivery.

You are trying to confuse the concept. In V2Ray, bittorrent refers to the BitTorrent protocol, not a service.

**Comment by database64128** [comment]
> In V2Ray, bittorrent refers to the BitTorrent protocol, not a service.

The definition says uTP is a "UDP-based variant of the BitTorrent peer-to-peer file sharing protocol".

> You are trying to confuse the concept.

I'm not trying to confuse anyone. In fact, many users are actually surprised that the previous bittorrent sniffer does not cover uTP:

- #93
- #1042
- #1044

By adding uTP sniffing capability directly to the existing bittorrent sniffer, as @nekohasekai did in previous commits, users can expect fewer surprises, less confusion, and generally a better experience.

**Comment by AkinoKaede** [comment]
I am looking for a better solution, this Pull Request will be temporarily closed.

**Comment by wloot** [comment]
> > Actually, almost no one does not use `http` and `tls` sniffers at the same time, but they are separate.
> 
> TLS is a generic secure transport, its payload does not have to be HTTP.
> 
> uTP was specifically designed for BitTorrent.
> 
> > Micro Transport Protocol or μTP (sometimes also uTP) is an open UDP-based variant of the BitTorrent peer-to-peer file sharing protocol intended to mitigate poor latency and other congestion control problems found in conventional BitTorrent over TCP, while providing reliable, ordered delivery.

Not really, since we are only sniffing hostname from TLS, it can basically be treated as HTTPS here.

**Comment by database64128** [comment]
> Not really, since we are only sniffing hostname from TLS, it can basically be treated as HTTPS here.

No, the SNI in TLS client hello is a part of TLS, not HTTPS.

**Pull request closed without merging**
