### PR TITLE
Support custom http proxy outbound header

### PR DESCRIPTION
**Pull request by mnixry**
```diff
{
  "protocol": "http",
  "settings": {
    "servers": [
      {
        "address": "server.example.com",
        "port": 443,
        "users": [
          {
+                "headers": {
+                  "Foo": "bar"
+               }
          }
        ]
      }
  }
}
```

### CODE REVIEW

**Review by kallydev — APPROVED** [review]

**Comment by AkinoKaede** [comment]
I think the `headers` could be add to `account`, and the config will be:

```diff
{
  "outbounds": [
    {
      "protocol": "http",
      "settings": {
        "servers": [
          {
            "address": "1.1.1.1",
            "port": 23333,
+           "headers": {
+             "X-Foo-Bar": "baz"
+            }
          }
        ]
      }
    }
  ]
}
```

**Comment by mnixry** [comment]
> I think the `headers` could be add to `account`

I would actually like to do this, but such a change would require very large changes to the existing code.

Since the `servers` field is filled in with an interface that is the same for all outbound protocols, modifying it could cause a lot of unnecessary changes

But I'm really not familiar with V2Ray's code, so can you point me in the right direction on how to do this?

**Comment by AkinoKaede** [comment]
> > I think the `headers` could be add to `account`
> 
> I would actually like to do this, but such a change would require very large changes to the existing code.
> 
> Since the `servers` field is filled in with an interface that is the same for all outbound protocols, modifying it could cause a lot of unnecessary changes
> 
> But I'm really not familiar with V2Ray's code, so can you point me in the right direction on how to do this?

Not, It will be a simple change. You can modify the `v2ray.core.proxy.http.Account`.

https://github.com/v2fly/v2ray-core/blob/b960d3f1fb9806dc7e2c73899342edb6b124bb70/proxy/http/config.proto#L11-L14

Here is a exmaple:

https://github.com/v2fly/v2ray-core/blob/b960d3f1fb9806dc7e2c73899342edb6b124bb70/proxy/http/client.go#L151-L155

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> It has been open 120 days with no activity. Remove stale label or comment or this will be closed in 5 days

Remove stale label

**Pull request closed without merging**
