### PR TITLE
Feat: add disableFallback & skipFallback option for DNS client

### PR DESCRIPTION
**Pull request by Loyalsoldier**
The default DNS querying order for now is match then query from top to bottom.

With this `skipFallback` option set to `true` in a specific DNS client, this DNS client will NOT be chose while in fallback querying process. You can use this option to skip DNS clients in China mainland during fallback.

With this `disableFallback` option set to `true`, the DNS querying order will be like this:

1. Match domain in DNS clients that are with `domains` option
2. If there are matches, use those clients accordingly
3. If no match, use the first DNS client set in config (not to use clients from top to bottom anymore)
4. If all queries failed, then return `nil` IP for domain, then that domain will use default outbound

The purpose of these two options are to avoid DNS leak when performing DNS resolution. They are mutually exclusive, in other words, the `skipFallback` will NOT take effect when `disableFallback` is set to `true`.

Fixes https://github.com/v2fly/v2ray-core/issues/750

### CODE REVIEW

**Comment by rurirei** [comment]
#750 is of the issue about the order in DNSObject.

dns query should designed to send requests by order, as Options added here is much complicated in my opinion.

**Comment by Loyalsoldier** [comment]
> #750 is of the issue about the order in DNSObject.
> 
> dns query should designed to send requests by order, as Options added here is much complicated in my opinion.

The key here is to disable fallback for all DNS clients or skip fallback for some DNS clients. And if you don't use these two options, then it remains the same as the original behavior. Use it or not, it's up to you.

**Comment by kslr** [comment]
Maybe there is a better plan.

**Comment by Loyalsoldier** [comment]
> Maybe there is a better plan.

What better plan?

**Comment by rurirei** [comment]
> With this skipFallback option set to true in a specific DNS client, this DNS client will NOT be chose

just delete the server from configuration.

> With this disableFallback option set to true, the DNS querying order will be like this:
Match domain in DNS clients that are with domains option
If no match, use the first DNS client set in config (not to use clients from top to bottom anymore)

just make a ordered configuration.

**Comment by Loyalsoldier** [comment]
@rurirei 

You didn't get it. We are talking about DNS leak during fallback DNS query after the first match failed.

Let's say we have these DNS in config:

```
{
    "dns": {
        "servers": [
            "https://1.1.1.1/dns-query",
            {
                "address": "https+local://223.5.5.5/dns-query",
                "domains": [
                    "geosite:cn"
                ]
            },
           "119.29.29.29",
           "localhost"
        ]
    }
}
```

`localhost` here will match `geosite:private` by default, but it  and `119.29.29.29`will also match all domains that are not in `geosite:cn` after `https://1.1.1.1` failed, eg: `https://1.1.1.1` failed to query the IPs of `google.com`, then `223.5.5.5` and the later ones will have DNS leak on `google.com`.

This DNS leak is NOT acceptable for some uses. And you can disable fallback or skip fallback on some DNS clients in China mainland to avoid it.

**Comment by rurirei** [comment]
@Loyalsoldier i mean it's not necessary to add much options to makes code more complicated. the requirement would be simply done by **domains:[] and conf-order**. and if user don't want to use some dnsserver to meet dns leak, why don't simply delete it from config?

```jsonc
{
    "dns": {
        "servers": [
            {
                "address": "https+local://223.5.5.5/dns-query",
                "domains": [
                    "geosite:cn"
                ]
            },
            {
                "address": "119.29.29.29",
                "domains": [
                    "geosite:cn"
                ]
            },
           "https://1.1.1.1/dns-query",
           "119.29.29.29",  // why don't delete this if don't want to use to
           "localhost"
        ]
    }
}
```

**Comment by Loyalsoldier** [comment]
`google.com` will match nothing, and will use `223.5.5.5` first, then DNS leak. As long as you set a DNS client in China mainland, there always have DNS leak, because your `geosite` data is NOT include all domains in the world.

**Comment by chromer030** [comment]
@Loyalsoldier , Thank you developing this option, Should we add something in config for this ?
No any info on https://www.v2fly.org/config/dns.html

**Comment by Loyalsoldier** [comment]
> @Loyalsoldier , Thank you developing this option, Should we add something in config for this ?
> No any info on https://www.v2fly.org/config/dns.html

Done.

**Pull request merged**
