### PR TITLE
Websocket Early Data and Browser forwarder Improvement

### PR DESCRIPTION
**Pull request by xiaokangwang**
This is a improvement of Web-Sockets transport that allow WebSocket connection to send early data in path, which reduce the WebSocket's connection establishment time, and browser forward, which will use any browser's WebSocket framework to automatically relay the traffic, which will have the same TLS fingerprint as browser initialized WSS traffic.

@rprx 已经要求我不能早于其发布此改进。

### CODE REVIEW

**Comment by xiaokangwang** [comment]
browser forwarder config: set this at root configure document
```
{
  "browserForwarder": {
    "listenAddr": "127.0.0.1",
    "listenPort": 1922
  }
}
```

**Comment by xiaokangwang** [comment]
websocket setting:
maxEarlyData = enable 0rtt early data
useBrowserForwarding = enable client browser forwarding(server-side support will be enabled automatically)

```      "streamSettings": {
        "network": "ws",
        "security": "none",
        "wsSettings": {
          "path": "/",
          "maxEarlyData": 1024,
          "useBrowserForwarding": true 
        },
        "tlsSettings": {
          "allowInsecure": false
        }
      }```

**Comment by rurirei** [comment]
i do not liked on near changes that add new Object at root configuration: FakeDNSObject and BrowserForwarderObject, as this break the past infrastructure of v2ray root configuration: log, dns, inbounds, outbounds, routing, etc. could you move these?

**Comment by xiaokangwang** [comment]
> i do not liked on near changes that add new Object at root configuration: FakeDNSObject and BrowserForwarderObject, as this break the past infrastructure of v2ray root configuration: log, dns, inbounds, outbounds, routing, etc. could you move these?

I have to say that, FakeDNS, BrowserForwarder are top level component of V2Ray instance, and it is most trivial to put them in the root document.

What kind of change would you suggest to make?

**Comment by rurirei** [comment]
@xiaokangwang like this.
```json
{
  "common": {
     "fakedns": {},
     "browserforwarder": {}
  }
}
```

**Comment by xiaokangwang** [comment]
> @xiaokangwang like this.
> 
> ```json
> {
>   "common": {
>      "fakedns": {},
>      "browserforwarder": {}
>   }
> }
> ```

Still waiting for opinion from @kslr

**Comment by kslr** [comment]
This is a terrible idea

**Comment by Loyalsoldier** [comment]
It seems there is an issue about safety: https://github.com/v2fly/v2ray-core/pull/818/checks?check_run_id=2210672378

**Comment by xiaokangwang** [comment]
> It seems there is an issue about safety: https://github.com/v2fly/v2ray-core/pull/818/checks?check_run_id=2210672378

I believe there is a check below that discard any unrecognized user supplied value.

**Pull request merged**
