### PR TITLE
chore fixed

### PR DESCRIPTION
**Pull request by Machtergreifung**
this pull request is binded with https://github.com/v2fly/v2ray-core/pull/1520 (that branch is deleted by me carelessly)

### CODE REVIEW

**Comment by AkinoKaede** [comment]
Why not commit these changes to the same branch?

**Comment by Machtergreifung** [comment]
i think all are here

**Comment by database64128** [comment]
Can't you make commits properly in your local dev environment? You are spamming everyone's inbox with useless commits.

**Comment by database64128** [comment]
Just look at https://github.com/v2fly/v2ray-core/actions. It's now full of useless workflow runs.

**Comment by database64128** [comment]
Closed for spamming.

**Pull request closed without merging**
