### PR TITLE
Fix TCP Keep-Alive (initial) interval.

### PR DESCRIPTION
**Pull request by ValdikSS**
The previous commit ab6480ef729509bc269e804a4f3de073fd33c657 changed incorrect parameter.
It applied keep-alive interval to TCP_KEEPINTVL, but it should be applied to TCP_KEEPIDLE instead.

>TCP_KEEPIDLE (since Linux 2.4)
>        The  time  (in  seconds)  the  connection needs to remain idle before TCP starts sending keepalive probes, if the socket option SO_KEEPALIVE has been set on this socket.  This option should not be used in code intended to be portable.
>
>TCP_KEEPINTVL (since Linux 2.4)
>        The time (in seconds) between individual keepalive probes.  This option should not be used in code intended to be portable.

This pull-request disables golang keep-alive handling and set up everything manually properly.

Fixes https://github.com/v2ray/v2ray-core/issues/2564

### CODE REVIEW

**Comment by ValdikSS** [comment]
Oh no, this does not fix the issue, and the commit description is incorrect.
**DO NOT MERGE YET.**

**Comment by ValdikSS** [comment]
All right, this is a proper fix.

**Comment by ValdikSS** [comment]
Please approve build action one more time. I hope this time it would build on all OSes.

**Comment by ValdikSS** [comment]
…once again please.

**Comment by ValdikSS** [comment]
Should I fix liter warnings or that's fine? Non-capitalized Tcp was used before this pull-request.

**Review by xiaokangwang — APPROVED** [review]
Thanks for your contribution. This fix will be merged after next stable release.

**Comment by xiaokangwang** [comment]
The lint can be easily fixed. You can fix or it will be fixed after merge.

**Comment by ValdikSS** [comment]
> The lint can be easily fixed. You can fix or it will be fixed after merge.

I'm not familiar with protobuf (as well as with golang), and it seems that changing the parameter name would require rebuilding raw bytes (rawDesc). I would appreciate any help. Or you can just leave it as-is.

**Review by kslr — APPROVED** [review]

**Comment by ValdikSS** [comment]
This patch sets keep-alive in case for listening sockets only for listening socket. At least on Linux, it is inherited for `accept()`'ed socket, but the internet tells me that socket options should be set to connected sockets.
I'm not aware how is it on other platforms. Should I call setsockopt for accept()'ed socket as well?

**Comment by database64128** [comment]
> Should I call setsockopt for accept()'ed socket as well?

Didn't you already set this in `applyOutboundSocketOptions`?

**Comment by ValdikSS** [comment]
> > Should I call setsockopt for accept()'ed socket as well?
> 
> Didn't you already set this in `applyOutboundSocketOptions`?

No unfortunately. For this you need to inherit `accept` I guess.

**Review by xiaokangwang — COMMENTED** [review]
During the merging & testing process, I have discovered some additional issues with your pull request. I would like to request you to justify your design before this merge request can proceed.

* Custom System Call is used when Go language's standard library [supports](https://pkg.go.dev/net#ListenConfig) setting this value. Is it possible to just set this value at transport/internet/system_dialer.go:70, or transport/internet/system_listener.go:58 ?
* The default behaviour is changed: by default Go language's standard library have a 15s keepalive interval. After applying this pull request, this value is increased to about 10 minutes.  An attacker on privileged network access may detect the change of behaviour and discover the usage of V2Ray easily by observing the change of behaviour.
* First KA packet sent Keep-Alive seconds after last data, then the system default TCP_KEEPINTVL will be used. This can generate a unique signature that identifies V2Ray.

Some additional thoughts are not relevant to the review of this pull request: It is not currently possible to hide that network sockets are created by a go language program when it comes to TLS connections. If an attacker can detect: a go language program created this TLS connection, a non-default keep alive interval is applied, it may be able to detect this connection is likely to be created by V2Ray.

**Comment by ValdikSS** [comment]
> Custom System Call is used when Go language's standard library [supports](https://pkg.go.dev/net#ListenConfig) setting this value. Is it possible to just set this value at transport/internet/system_dialer.go:70, or transport/internet/system_listener.go:58 ?

No, because it sets both TCP_KEEPINTVL and TCP_KEEPIDLE and does not allow to configure them separately. This is totally incorrect behavior of golang in my opinion. Linux uses 9 keep-alive probes of TCP_KEEPINTVL interval before closing the socket, so setting dial.Dialer or Listener KeepAlive to 300 seconds (5 minutes) gives _50 minutes_ of actual socket hang detection.  
If golang could set only TCP_KEEPIDLE and not touch TCP_KEEPINTVL, 300 second KeepAlive with the default Linux behavior (TCP_KEEPINTVL=75) would close the socket after ≈16 minutes, which is correct and expected. The latest behavior is widely used elsewhere.

I can change the code to use golang's KeepAlive (that sets TCP_KEEPIDLE and TCP_KEEPINTVL) and set proper TCP_KEEPINTVL with setsockopt(), but this would require to code accept() call handler, because golang would re-apply the settings on every socket accept and this is not currently handled (neither by v2ray or by the patch). Six of one and half a dozen of the other.

See more detailed issue description in golang repo: https://github.com/golang/go/issues/48622

> The default behaviour is changed: by default Go language's standard library have a 15s keepalive interval. After applying this pull request, this value is increased to about 10 minutes. An attacker on privileged network access may detect the change of behaviour and discover the usage of V2Ray easily by observing the change of behaviour.

This is true I guess. It adds a bit of information for the attacker compared to the default golang behavior which is widely used in other golang software. Please note however, that keep-alive would be activated only if the socket has been idle (or stale) for more than 10 minutes. In normal circumstances, the software (v2ray) itself will close the socket due to timeout, which is set to less than 10 minutes by default if I remember correctly.  
I assume the software is written with a careful eye to Chinese users generally, and I'm not very savvy in Chinese GFW (I'm from Russia). So, that's your decision.

> First KA packet sent Keep-Alive seconds after last data, then the system default TCP_KEEPINTVL will be used. This can generate a unique signature that identifies V2Ray.

Please note that overwhelming majority of software behave exactly this way: the timeouts for TCP_KEEPIDLE and TCP_KEEPINTVL are almost always different. The first is long, the other one is relatively short. This is exactly what keep-alive packets are for: they are designed to activate only when the connection does not send or receive data for a long amount of time, and probe for the peer for a short amount of time if no response has been received.  
Only golang software does it's own thing.

**Comment by xiaokangwang** [comment]
Thanks for your explanation. I have understood your reasoning for this design. I agree with your idea that TCP_KEEPINTVL, TCP_KEEPIDLE are able to be set separately. 

I have examined the code again, but I didn't find a way to set TCP_KEEPINTVL with the configuration file. I think this can be added to make sure that users can set this value separately.

I understand the usual way for any application to work with this kind of configuration is to accept the system-wide configuration. However, as an anti-censorship tool, it must attempt to blend into other similar software by default. Since it cannot hide the fact that it is a go language program. It will need to attempt to pretend to be a random go program, not V2Ray. And this should be the default behaviour.

As for this pull request, I believe it will be better if:
1. make both TCP_KEEPINTVL TCP_KEEPIDLE configurable in the configuration file.
2. if the user does not set either of the value(the value is 0), emulate the go language's default behaviour. This ensures that this tool does not leak user information by default.

**Comment by ValdikSS** [comment]
Implemented by @xiaokangwang in #1395, thanks for this!

**Pull request closed without merging**
