### PR TITLE
Support Speed Limit

### PR DESCRIPTION
**Pull request by kslr**
ref v2ray/v2ray-core#2674

我感觉命名不是很好，看看有没有改的

开启后会降低 4% 性能

只能工作在带用户信息的入站上（或者称为服务端

```bash
"policy": {
    "levels": {
        "0": {
            "inboundSpeed": "100M",
            "outboundSpeed": "100M"
         },
        "1": {
            "inboundSpeed": "10M",
            "outboundSpeed": "10M"
         }
    }
},
```

```bash
{
    "vnext": [
        {
            "address": "127.0.0.1",
            "port": 37192,
            "users": [
                {
                    "id": "27848739-7e62-4138-9fd3-098a63964b6b",
                    "level": 0
                },
                {
                    "id": "27848739-7e62-4138-9fd3-098a63964b6c",
                    "level": 1         
               }
            ]
        }
    ]
}

```

我正在等待时间重构，先不要处理它

### CODE REVIEW

**Comment by NutterChen** [comment]
Q:
The speed limit set here is the sum of the entire inbound or outbund speed?
Or will it limit the speed of each client (email or UUID)?

**Comment by kslr** [comment]
> Q:
> The speed limit set here is the sum of the entire inbound or outbund speed?
> Or will it limit the speed of each client (email or UUID)?

level
https://www.v2fly.org/config/policy.html#levelpolicyobject

**Comment by NutterChen** [comment]
> > Q:
> > The speed limit set here is the sum of the entire inbound or outbund speed?
> > Or will it limit the speed of each client (email or UUID)?
> 
> level (email)
> https://www.v2fly.org/config/policy.html#levelpolicyobject

thx

**Comment by TalosPan** [comment]
regarding the level of speed limit strategy, it seems not so practical and attractive. Do u consider working on each client by email?

**Comment by kslr** [comment]
> regarding the level of speed limit strategy, it seems not so practical and attractive. Do u consider working on each client by email?

I think it's enough.

**Comment by TalosPan** [comment]
> > regarding the level of speed limit strategy, it seems not so practical and attractive. Do u consider working on each client by email?
> 
> I think it's enough.

other hand, seems that no api related to this new feature has been written

**Comment by NutterChen** [comment]
> regarding the level of speed limit strategy, it seems not so practical and attractive. Do u consider working on each client by email?

+Reconsideration

**Comment by crossfw** [comment]
请问有人试过多线程的限速效果吗，我发现只有将 [app/dispatcher/speed/bucket.go#L25](https://github.com/v2fly/v2ray-core/blob/0079bf970647e6f638b53f864a2a415a06893c37/app/dispatcher/speed/bucket.go#L25) 的超时时间调大（大约300ms后有效果，我调到了1s）才对多线程有效。

**Pull request closed without merging**
