### PR TITLE
update observatory implemtation

### PR DESCRIPTION
**Pull request by xqxrrz1ge2**
#1478 #1479

### CODE REVIEW

**Review by AkinoKaede — CHANGES_REQUESTED** [review]
I disagree with this changes, `ProbeInterval` should be the probe interval for each outbound.

**Comment by xqxrrz1ge2** [comment]
> I disagree with this changes, `ProbeInterval` should be the probe interval for each outbound.

That's reasonable. 
However, if I have several balancerTags in routing rule, the balancerTag won't take effect unless a probe is probed.

Say we have 4 outbounds, like to-default01, to-default02, to-jp01, to-jp02. 

And create 2 balancerTags for them to-default and to-jp, the outbounds will be probed in this order, to-default01--interval-->to-default02--interval-->to-jp01--interval-->to-jp02, since they are sorted, right?

If I have below rules, this rule will not take effect unless the to-jp01 is probed, which will take interval * 2 time.
The more outbounds you have, more time you will need to wait.
I'm not sure whether this is intended or something, and it's okay not to merge this since the Version 5 would like to have a concurrency support for probing. 

{
        "type": "field",
        "domain": [
          "geosite:google"
        ],
        "balancerTag": "to-jp"
},

**Comment by kslr** [comment]
Concurrency may be a better option.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> If I have below rules, this rule will not take effect unless the to-jp01 is probed, which will take interval * 2 time. The more outbounds you have, more time you will need to wait. I'm not sure whether this is intended or something, and it's okay not to merge this since the Version 5 would like to have a concurrency support for probing.

`probeInterval * outbounds` + outbounds probe latency 
for 250ms outbound latency, it will take +1 second in example of 4 outbounds, +1 second per `probeInterval`

Yes, it is annoying while bootstrapping run, waiting for outbounds to come available.

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> It has been open 120 days with no activity. Remove stale label or comment or this will be closed in 5 days

Remove stale label

**Comment by 4-FLOSS-Free-Libre-Open-Source-Software** [comment]
> It has been open 120 days with no activity. Remove stale label or comment or this will be closed in 5 days

Remove stale label

**Pull request closed without merging**
