### PR TITLE
feat: RandomStrategy AliveOnly

### PR DESCRIPTION
**Pull request by mkmark**
Address #1841.

New optional settings to strategy `random`: `aliveOnly` and `observerTag`.

If `aliveOnly == true`, enable the strategy to choose only from alive outbounds. Outbounds are considered alive unless proven otherwise (by observatory).

Very useful when one has several unstable outbounds, this improves reliability by making these outbounds fail-safe to each other.

Also useful when one wants to combine bandwidth of several unstable outbounds.

Use like

```json
{
  "selector": [
    "a",
    "b"
  ],
  "tag": "c",
  "strategy": {
    "type": "random",
    "settings": {
       "aliveOnly": true
    }
  }
}
```

Need `observatory`.

## FAQ

> How much does this affect the original `random` strategy?

Fully compatible with the original `random` strategy, i.e. no strategy at all.

It adds a check upon picking an outbound, i.e. whether ones has a `random strategy`. Almost no performance effect.

<details><summary>obsolete</summary>
New balancer strategy: `randomalive`.

Random, but only choose from alive outbounds.

Use like

```json
{
  "selector": [
    "a",
    "b"
  ],
  "tag": "c",
  "strategy": {
    "type": "randomalive"
  }
}
```
</details>

### CODE REVIEW

**Comment by xiaokangwang** [comment]
Thanks for you contribution. I think this merge request is ready to be merged.

**Comment by xiaokangwang** [comment]
This pull request have been merged. Please send a pull request to the document if you are willing and able.

**Comment by miladrahimi** [comment]
Does this feature works for round-robin strategy too?

**Comment by mkmark** [comment]
> Does this feature works for round-robin strategy too?

I guess that's a feature of Xray-core, which is not implemented here.

**Comment by mkmark** [comment]
> This pull request have been merged. Please send a pull request to the document if you are willing and able.

https://github.com/v2fly/v2fly-github-io/pull/454

**Pull request merged**
