### PR TITLE
Compatibility change for go 1.18

### PR DESCRIPTION
**Pull request by MoetaYuko**

### CODE REVIEW

**Comment by AkinoKaede** [comment]
The version in `go.mod` should be change to 1.18. However, is it necessary to maintain compatibility with Go 1.18?

**Comment by MoetaYuko** [comment]
> The version in `go.mod` should be change to 1.18.

It was changed to 1.19 in https://github.com/v2fly/v2ray-core/commit/9ae51c1f15de1af155c12b134ef929f69adf4660, and at that time 1.18 was still supported. I'm unsure how to deal with it but should be irrelevant to this PR IMHO.

> However, is it necessary to maintain compatibility with Go 1.18?

The reason is two-fold:
1. OpenWRT 21.02 (a.k.a. "oldstable") uses go 1.18 and it's unlikely that the branch will receive new updates of go.
2. The extra effort to support 1.18 is really trivial for now at least.

**Comment by AkinoKaede** [comment]
The version in go.mod specifies the minimum version to use. For normative reasons, this field should be changed if support for Go 1.18 is to be maintained. 

> The go directive in a go.mod file now indicates the version of the language used by the files within that module. It will be set to the current release (go 1.12) if no existing version is present. If the go directive for a module specifies a version newer than the toolchain in use, the go command will attempt to build the packages regardless, and will note the mismatch only if that build fails. [Go 1.12 Release Notes](https://golang.org/doc/go1.12#modules)

**Comment by MoetaYuko** [comment]
> `qtls.CipherSuiteTLS13` and `qtls.AEADAESGCMTLS13` in different qtls versions are just the same thing. It is possible to embed them into v2ray to remove those annoying `qtls-go1-xx` dependencies.

This is how Xray deal with the issue https://github.com/XTLS/Xray-core/commit/00c95761189162504ebc2c0df3266e9395c7e40d, but I'm wondering if it'll silently break stuff if qtls changes them in the future.

I'm personally open to both solutions.

**Comment by MoetaYuko** [comment]
@AkinoKaede Any updates? Which solution is preferred?

**Comment by AkinoKaede** [comment]
My concern is that V2Ray may not support Go 1.18 in the long term. quic-go will stop supporting Go 1.18 when Go 1.21 is officially released, as a rule.

**Comment by AkinoKaede** [comment]
c.c. @xiaokangwang

**Comment by xiaokangwang** [comment]
I agree that QUIC is problematic, but I think we could not keep the compatibility with a certain version of Go tool chain indefinitely.

Is there anything preventing this change from being send to OpenWRT's distro repo, which is prefer for this kind of distro specific changes?

**Comment by MoetaYuko** [comment]
> I agree that QUIC is problematic, but I think we could not keep the compatibility with a certain version of Go tool chain indefinitely.

Of course, it's infeasible to keep compatibility with go 1.18 forever. However, I think it's fair to add the compatibility for now at least considering the trivial extra effort. Besides, v2ray itself is buildable with go 1.18 but a dependence (QUIC). It's more reasonable to drop support for old go releases when v2ray strictly relies on features from new go releases.
> 
> Is there anything preventing this change from being send to OpenWRT's distro repo, which is prefer for this kind of distro specific changes?

Yes and no. For building v2ray itself we can simply patch it. But for packages using v2ray as a go dependence (e.g. https://github.com/teddysun/v2ray-plugin/blob/b06bccfb77fd7f1fad4769302e47967ad7dbd8d7/go.mod#L7), I'm not aware of any built-in mechanism to patch it.

**Comment by xiaokangwang** [comment]
I think it is fine to merge this and buy OpenWRT more time to deal with their slow update issue and make things easier for you. It should be remembered that this is a temporary measure, and will not be kept indefinitely.

I don't think it is possible to get rid of QUIC now with selective compile since it is imported by app/dns, so we will have to drop support for go 1.18 when QUIC stop support it.

**Comment by MoetaYuko** [comment]
Rebased just now to resolve conflicts.

> I think it is fine to merge this and buy OpenWRT more time to deal with their slow update issue and make things easier for you. It should be remembered that this is a temporary measure, and will not be kept indefinitely.

22.03 and upwards have migrated to newer golang releases so ig 21.02 will stay 1.18 forever. Nonetheless, support for 21.02 will be dropped soon after 23.xx release this year, so this "temporary" change should be sufficient before 21.02 eol.

**Comment by MoetaYuko** [comment]
`quic-go` 0.33.0 is no longer buildable with go 1.18, so this becomes a no-op now and can be reverted.
> It's happening so faaaast

**Comment by AkinoKaede** [comment]
:(

**Pull request merged**
