### PR TITLE
feat: support url as config input

### PR DESCRIPTION
**Pull request by heart4lor**
support start with config url, e.g. v2ray run -c http://localhost/v2ray/server/common1

### CODE REVIEW

**Comment by AkinoKaede** [comment]
https://github.com/v2fly/v2ray-core/blob/f9422d60aabb85ca56659025fda3dae2dc8340f3/common/common.go#L129

**Comment by heart4lor** [comment]
code style formatted.

**Comment by heart4lor** [comment]
> Please use ·`github.com/v2fly/v2ray-core/v5/common.FetchHTTPContent`
> 
> https://github.com/v2fly/v2ray-core/blob/f9422d60aabb85ca56659025fda3dae2dc8340f3/common/common.go#L129-L162

My bad. Fixed

**Comment by heart4lor** [comment]
Test failed because of https://github.com/v2fly/v2ray-core/pull/2083

**Comment by AkinoKaede** [comment]
Should we re-add this feature?  I have no opinion. cc. @xiaokangwang @qjebbs

**Comment by xiaokangwang** [comment]
The reason I have disabled this in the first place is that is function is not very designed and have potential issues.

- the configuration file often include local information like filename or port number that is not typically predictable for remote network devices.
- there is no auto update built in, so there is no way to get it updated based on http/https protocol alone.

I suggest that this be implemented with a wrapper script or ExecStartPre in systemd until we can implement it correctly in a way that is practical useful.

**Comment by heart4lor** [comment]
> And more, can use pipe grammar to do this with `-config=stdin:`.
> 
> For example,
> 
> `curl -sL https://github.com/v2fly/v2ray-core/raw/master/release/config/config.json|./v2ray -test -config=stdin:`

For many container environment, there's no `curl` binary in the image.

**Comment by xiaokangwang** [comment]
> > And more, can use pipe grammar to do this with `-config=stdin:`.
> > For example,
> > `curl -sL https://github.com/v2fly/v2ray-core/raw/master/release/config/config.json|./v2ray -test -config=stdin:`
> 
> For many container environment, there's no `curl` binary in the image.

Is there something that you cannot solve with building a custom container image with a "FROM" to import the v2ray binary from a existing v2ray image?

I understand that this useful in container environments, but it could encourage use a configuration file as a subscription format, which is not recommended.

**Pull request closed without merging**
