### PR TITLE
Add traffic stat of every request in access log

### PR DESCRIPTION
**Pull request by zhi1ong**
#640

### CODE REVIEW

**Review by database64128 — CHANGES_REQUESTED** [review]
It'd be better to specify data unit in variable names and log messages. For example, `BytesSent` and `BytesReceived`.

**Comment by database64128** [comment]
Thank you for your contribution! 🎉

**Comment by chromer030** [comment]
This feature is great , but i tested now and has bug , nothing shows :

```$ ./v2ray -c C.json
V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.7 linux/amd64)
A unified platform for anti-censorship.
2021/01/29 21:46:37 [Info] v2ray.com/core/main/jsonem: Reading config: C.json
2021/01/29 21:46:37 [Warning] v2ray.com/core: V2Ray 4.34.0 started
2021/01/29 21:46:51 tcp:127.0.0.1:35880 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:02 tcp:127.0.0.1:35942 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:02 tcp:127.0.0.1:35958 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:02 tcp:127.0.0.1:35960 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:02 tcp:127.0.0.1:35934 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:02 tcp:127.0.0.1:35940 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:56 tcp:127.0.0.1:35898 accepted tcp:fonts.gstatic.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:57 tcp:127.0.0.1:36006 accepted tcp:www.google.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:57 tcp:127.0.0.1:35994 accepted tcp:www.google.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:47:57 tcp:127.0.0.1:36000 accepted tcp:www.google.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:48:08 tcp:127.0.0.1:36018 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:48:12 tcp:127.0.0.1:35910 accepted tcp:r6---sn-nx5e6ne6.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:48:12 tcp:127.0.0.1:36024 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
2021/01/29 21:48:14 tcp:127.0.0.1:36030 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0```

**Comment by kslr** [comment]
I think more review is needed, This implementation is too "hack"

**Comment by zhi1ong** [comment]
> This feature is great , but i tested now and has bug , nothing shows :
> 
> ```
> V2Ray 4.34.0 (V2Fly, a community-driven edition of V2Ray.) Custom (go1.15.7 linux/amd64)
> A unified platform for anti-censorship.
> 2021/01/29 21:46:37 [Info] v2ray.com/core/main/jsonem: Reading config: C.json
> 2021/01/29 21:46:37 [Warning] v2ray.com/core: V2Ray 4.34.0 started
> 2021/01/29 21:46:51 tcp:127.0.0.1:35880 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:02 tcp:127.0.0.1:35942 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:02 tcp:127.0.0.1:35958 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:02 tcp:127.0.0.1:35960 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:02 tcp:127.0.0.1:35934 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:02 tcp:127.0.0.1:35940 accepted tcp:yt3.ggpht.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:56 tcp:127.0.0.1:35898 accepted tcp:fonts.gstatic.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:57 tcp:127.0.0.1:36006 accepted tcp:www.google.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:57 tcp:127.0.0.1:35994 accepted tcp:www.google.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:47:57 tcp:127.0.0.1:36000 accepted tcp:www.google.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:48:08 tcp:127.0.0.1:36018 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:48:12 tcp:127.0.0.1:35910 accepted tcp:r6---sn-nx5e6ne6.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:48:12 tcp:127.0.0.1:36024 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
> 2021/01/29 21:48:14 tcp:127.0.0.1:36030 accepted tcp:r6---sn-a5mekn7r.googlevideo.com:443 bytes_sent: 0 bytes_received: 0
> ```

Statistics feature need to be turned on before testing  ==> https://www.v2ray.com/chapter_02/stats.html

**Comment by database64128** [comment]
My bad 😅

Revert for now. The feature needs more polishing before it can be merged.

**Pull request merged**
