### PR TITLE
Support "services" root config in cfgv4

### PR DESCRIPTION
**Pull request by Vigilans**
This allows tun to be configured in v4cfg:
```
  "services": {
    "tun": {
      "name": "tun0",
      "mtu": 1500,
      "tag": "tun",
      "ips": [{ "ip": [198, 18, 0, 0], "prefix": 15 }],
      "routes": [
         { "ip": [0, 0, 0, 0], "prefix": 0 }
         // , { "ip": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], "prefix": 0 }
      ],
      "enablePromiscuousMode": true,
      "enableSpoofing": true
    }
  }
```
Fixes https://github.com/v2fly/v2ray-core/pull/2541#issuecomment-2076989572

### CODE REVIEW

**Comment by Losalado** [comment]
Great, thanks!

**Review by Losalado — APPROVED** [review]

**Comment by xiaokangwang** [comment]
I think this merge request is ready to be merged. A merge request for its document is welcomed! To process merge request faster, documentation task will no longer be a release blocker.

**Comment by Losalado** [comment]
@Vigilans I have used this to activate tun,but it seems that tun0 does not get any ip packet from local networks. Assuming that tun0 is 192.18.0.1/15, and LAN devices are 192.168.0.0/24, the v2ray is on a server with tun0 192.18.0.1 and lan 192.168.0.2, could you please help suggest proper ip rule/route to make ip packets from 192.168.0.0/24 to 192.18.0.1/15 are routed to tun0. It should be common case for fakedns and tun. Thanks~

**Comment by Losalado** [comment]
> @Vigilans I have used this to activate tun,but it seems that tun0 does not get any ip packet from local networks. Assuming that tun0 is 192.18.0.1/15, and LAN devices are 192.168.0.0/24, the v2ray is on a server with tun0 192.18.0.1 and lan 192.168.0.2, could you please help suggest proper ip rule/route to make ip packets from 192.168.0.0/24 to 192.18.0.1/15 are routed to tun0. It should be common case for fakedns and tun. Thanks~

I would like to paste ip rule/route command I have tried:

ip link set tun0 up
ip addr add 192.18.0.1/15 dev tun0

ip rule add from 192.168.0.0/24  to 192.18.0.0/15 table 10
ip route add default dev tun0 table 10

**Comment by Losalado** [comment]
Sorry, I habe mistake of confusing 192.18.0.1 and 198.18.0.1. It works in my device.
Many thanks for your job.

**Comment by yyiu** [comment]
`V2Ray 5.22.0 (go1.23.2 linux/amd64)

2024/11/02 03:12:49 Using confdir from arg: /usr/local/etc/v2ray

Failed to start: app/tun: failed to create device > app/tun/device/gvisor: failed to open tun device > no such file or directory
`

**Comment by yyiu** [comment]
`V2Ray 5.22.0 (go1.23.2 linux/amd64)

2024/11/02 03:12:49 Using confdir from arg: /usr/local/etc/v2ray

Failed to start: app/tun: failed to create device > app/tun/device/gvisor: failed to open tun device > no such file or directory`

**Comment by Toskies** [comment]
> It works in my device now. Many thanks for your job.
您好，请问您用的哪个版本的v2ray，或者配置怎么写的呢？我的一直配置不好

**Comment by Losalado** [comment]
> > It works in my device now. Many thanks for your job.
> 
> 您好，请问您用的哪个版本的v2ray，或者配置怎么写的呢？我的一直配置不好
> 
> 

PR上面有给示例，可以看看按上面的写法有没有报错？版本应该用最新的就可以，我一直都会更新。

**Pull request merged**
