### PR TITLE
Feat: add reverse match for GeoIP

### PR DESCRIPTION
**Pull request by Loyalsoldier**
Now you can reverse match GeoIP in Routing and DNS expectIPs like this:

```
geoip:!cn
ext:/path/to/third-party/geoipfile:!cn
ext-ip:/path/to/third-party/geoipfile:!cn
```

Related issue: https://github.com/v2ray/v2ray-core/issues/2177

### CODE REVIEW

**Review by kslr — APPROVED** [review]
Although "reverse" sounds a bit weird

**Comment by Loyalsoldier** [comment]
> Although "reverse" sounds a bit weird

Any better words?

**Comment by CalmLong** [comment]
反向匹配会有性能问题吗

**Comment by Loyalsoldier** [comment]
> 反向匹配会有性能问题吗

不会啊，就判断是否需要反向匹配，然后对原有匹配结果进行取反。比原本多了两步而已。

**Comment by LazyZhu** [comment]
Add reverse match support for geosite.dat?
@Loyalsoldier

**Comment by Loyalsoldier** [comment]
> Add reverse match support for geosite.dat?
> @Loyalsoldier

I think it's unnecessary. You can achieve this in V2Ray routing easily.

**Comment by redstoneleo** [comment]
1. geoip:!cn这种写法在哪个客户端里可以用？
2. 我在v2rayN客户端里只写了geoip:cn，发现没有匹配的也自动走代理了，真神奇

**Pull request merged**
