### PR TITLE
feat: core.ToContext(ctx, v) for ctx initialization

### PR DESCRIPTION
**Pull request by rurirei**
related #831 #841 

this brings a method to check and create Instance for ctx, while may someone needs this. (like me ::)

### CODE REVIEW

**Review by kslr — APPROVED** [review]

**Review by Loyalsoldier — APPROVED** [review]

**Comment by xiaokangwang** [comment]
Hi, I have to revert some of your change: you have created an exported API, which is an unsupported usage.

You shouldn't use
```
//go:linkname mustToContextForced github.com/v2fly/v2ray-core/v4.mustToContext
func mustToContextForced(ctx context.Context, v *Instance) context.Context
```
to forcefully export this function into your package to create a context suitable for interact with V2Ray's internal component.
This kind of usage is unsupported and may break at any time.

**Comment by rurirei** [comment]
@xiaokangwang ok. i don't know how to design a func MustToContext (i see there is a func MustFromContext as i created a similar one), and i wait for your opinion on this pr (sorry for no extra comment for this). you can do your way kindly, thanks.

**Comment by xiaokangwang** [comment]
The reason I did so is that V2Ray have so many internal components that may change behavior at any time, you shouldn't depend on them remain unchanged.  You could develop software that interact with them, but it may stop working any time.

**Comment by rurirei** [comment]
@xiaokangwang thanks for your explaination.

maybe there is a purpose to make a public ToContext(ctx, v) for go test. https://github.com/v2fly/v2ray-core/blob/1822504ed84bb0de4c41ca888680a6588dead2c2/app/proxyman/outbound/handler_test.go#L70

**Pull request merged**
