### PR TITLE
make MaxConnection larger than MaxConcurrency

### PR DESCRIPTION
**Pull request by runchard**

### CODE REVIEW

**Comment by runchard** [comment]
In the logic of https://github.com/v2fly/v2ray-core/blob/master/common/mux/client.go#L269-L287 
Higher concurrency setting (larger than 128) will be useless.
The MaxConnection have a higher precedence which should be loose and/or at least larger than the concurrency amount.

**Comment by kslr** [comment]
btw, why do you need  > 128

**Comment by runchard** [comment]
> btw, why do you need > 128

Good question. I don't think normal user will use such amount of connection.
And the `128` is also a magic number wait to be verified. Let's say, use `64` or `32` here?

But this PR is not intended to solve the why > 128 issue. Just provide a straight forward solution to make sure concurrency will working as configured.

**Review by xiaokangwang — CHANGES_REQUESTED** [review]
I think the obvious limit of Max Connection Mux is about 2^16 connections(because of SessionID ), but your making a change that would allow it to be as high as 2^32.

Other than that there is no test case for this kind of usage, so it can be troublesome since it will becomes a rarely used feature where bug can be hard to reproduce. 

The reason for limiting to 128 is probably because the need to use new connection from time to time to reduce the issue of stale connection and troublesome per connection QoS,  but I think this isn't a huge issue and increasing the limit of Mux  should be fine as long as:

- You do not introduce unintended change to behavior, if the configure file isn't changed, the behavior shouldn't

- You add test to prevent future change breaking high max connection Mux without being noticed.

**Comment by runchard** [comment]
Good point, then just insist with current status.

**Pull request closed without merging**
