### PR TITLE
proxy dns with NOTIMP error

### PR DESCRIPTION
**Pull request by robberphex**
Chromium will send SVCB/HTTPS type dns query, which cause dns leak.

To prvent dns leak, 
* If the dns query type is not implemented, should return NOTIMP error, not just send data to original destination.
* If the dns query has wrong format domain, should return FORMERR error, not send data to original destination.

### CODE REVIEW

**Comment by AkinoKaede** [comment]
Thanks, I think we need to discuss a more reasonable solution.

**Comment by robberphex** [comment]
> Thanks, I think we need to discuss a more reasonable solution.

Yes, but how? This has put the user in danger for years.

**Comment by robberphex** [comment]
> To prevent DNS leak, why not override destination address and configure `proxySettings` for `dns` outbound to make non-A/AAAA traffic routable?

1. Is there an example for this?
2. non-A/AAAA dns request will always to remote server, which is time-costing. And return NOTIMP error is reasonable.
3. v2ray provide route solution for "customized routing", throw HTTPS dns query will cause client/chromium waiting and use dns response. Returning NOTIMP can make client use dns response from v2ray.

**Comment by robberphex** [comment]
@AkinoKaede @dyhkwong `proxySettings` only has `tag` and `transportLayer` field, is captiable to split flow by domains.

For example, Chromium will send SVCB/HTTPS query for every domain, some chinese domain should only query in local network.

And currently, we don't have much resource to implement SVCB/HTTPS query type, and we cannot implement every query on time in futrue. So let's fllow spec, return NOTIMP.

Is there any other way to prevent this kind of dnsleak, and don't put the user in danger?

**Comment by AkinoKaede** [comment]
> @AkinoKaede @dyhkwong `proxySettings` only has `tag` and `transportLayer` field, is not captiable to split flow by domains.
> 
> For example, Chromium will send SVCB/HTTPS query for every domain, some chinese domain should only query in local network.
> 
> And currently, we don't have much resource to implement SVCB/HTTPS query type, and we cannot implement every query on time in futrue. So let's fllow spec, return NOTIMP.
> 
> Is there any other way to prevent this kind of dnsleak, and don't put the user in danger?

Another developer suggested configuring the `proxySettings` to route requests not supported by `dns app` to the `blackhole`.

**Pull request closed without merging**
