### PR TITLE
Fake DNS improvement: fakedns+others sniffer, muti stack(mutlti pool) fake dns

### PR DESCRIPTION
**Pull request by xiaokangwang**
Fakedns+others sniffer is a re-implementation of https://github.com/v2fly/v2ray-core/pull/697's idea. However, this implementation does not make any change to infrastructure code.

Muti stack(multi pool) DNS aimed at supporting fake DNS in IPv4 IPv6 dual stack environment, and should be able to return valid response based on request type. (https://github.com/v2fly/v2ray-core/issues/881)

### CODE REVIEW

**Comment by xiaokangwang** [comment]
There is currently a bug in the fakedns+others sniffer code, thinking about how to solve it...

**Comment by xiaokangwang** [comment]
OK, fixed. This introduced a minor change to matching logic, but do not introduce any breaking change to previous code.

Here is the config for fake dns + others:
```
"sniffing": {
        "enabled": true,
        "destOverride": [
          "fakedns+others",
          "fakedns"
        ],
        "metadataOnly": false
      }
```
here is the config for mutistack FakeDNS:
```
"fakeDns": {
    "pools": [
      {
        "ipPool": "88.88.88.88/12",
        "poolSize": 1024
      },
      {
        "ipPool": "fddd:c5b4:ff5f:f4f0::/64",
        "poolSize": 1024
      }
    ]
  }
```

**Comment by kslr** [comment]
GetFakeIPForDomain3 is other ?

**Comment by xiaokangwang** [comment]
> GetFakeIPForDomain3 is other ?

No, this is used for answering DNS request correctly since we need to reply IPv6 address(s) to AAAA request and IPv4 address(s) to A request.

**Pull request merged**
