### PR TITLE
add makefile

### PR DESCRIPTION
**Pull request by Machtergreifung**

### CODE REVIEW

**Comment by database64128** [comment]
I can't think of a scenario where this makefile would be useful. And there are other problems in your makefile:

1. Hardcoded version number: Adds more burden to maintenance.
2. Hardcoded CGO_ENABLED=0: You should enable CGO for local builds, which is probably the only scenario where you can get the makefile involved.

**Comment by Machtergreifung** [comment]
> 

thank you for your reply.may be use $(sed -n "21p"   core.go) will be better

**Comment by Machtergreifung** [comment]
> I can't think of a scenario where this makefile would be useful. And there are other problems in your makefile:
> 
> 1. Hardcoded version number: Adds more burden to maintenance.
> 2. Hardcoded CGO_ENABLED=0: You should enable CGO for local builds, which is probably the only scenario where you can get the makefile involved.

thank you for your reply.may be use $(sed -n "21p" core.go) will be better

**Comment by Machtergreifung** [comment]
> I can't think of a scenario where this makefile would be useful. And there are other problems in your makefile:
> 
> 1. Hardcoded version number: Adds more burden to maintenance.
> 2. Hardcoded CGO_ENABLED=0: You should enable CGO for local builds, which is probably the only scenario where you can get the makefile involved.

i refer to use makefile to build because i need not to type other command expect make

**Pull request closed without merging**
