### PR TITLE
V5: ping & links command

### PR DESCRIPTION
**Pull request by qjebbs**
This PR add 2 commands `ping` & `links`.

```
Examples:

    v2ray links vmess://... vmess://...   (1)
    v2ray links -t name -u url -o dir     (2)
    v2ray links -c path/to/json -o dir    (3)

(1) Convert links and save to current directory.
(2) Fetch and convert links from the subscription url.
(3) Fetch and convert links from multiple subscriptions.
```

## Useful?

Together with commands from recent PRs, v2ray now can:

1. fetch subscription with `v2ray links -u <url>`, save to: a.json, b.json...
1. check nodes with `v2ray ping a.json`, `v2ray ping b.json`...
1. add good nodes with  `v2ray api ado a.json`
1. remove bad nodes with  `v2ray api rmo b.json`
1. Repeat above steps with scheduled Tasks

I was hesitated to start this PR. If you have any concerns, like:

- `vmess://` links is not officially supported
- Codes are copied from `vmessping` project, but you may still want to keep it as an independent project
- Any other concerns

If so, feel free to close it, I am continue to keep them for my personal use.

~~### PS: Anyone knows why the test build are all failed??~~

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
The `v2ctl` builds

```shell
CGO_ENABLED=0 go build -o v2ctl -trimpath -ldflags "-s -w -buildid=" -tags confonly ./infra/control/main
```

 failed because there is a build tag `confonly`. And there is a line `// +build !confonly` in `v2ray.go`, so you can NOT init the v2ray instance in miniv2ray.

**Comment by kslr** [comment]
We are advancing https://github.com/v2fly/v2fly-github-io/issues/26
Welcome to post your thoughts

**Comment by qjebbs** [comment]
> confonly

Thanks again for your reply. Now that we have come to this part, shall we remove v2ctl now? #488

**Comment by qjebbs** [comment]
@kslr I feel it's pretty good.

Did you suggest that we should only support the official link format?

Regarding to my `links` command implementation, it's ugly though, Link is an interface:

```go
type Link interface {
	Tag() string
	Detail() string
	ToOutbound() *conf.OutboundDetourConfig
}
```
Works for `vmess://` and `vless://` in the future (if it would be there)

Parsing procedure of `vmess://` links, tries and fallback between different formats. We can add the official format then.

**Comment by kslr** [comment]
> @kslr I feel it's pretty good.
> 
> Did you suggest that we should only support the official link format?
> 
> Regarding to my `links` command implementation, it's ugly though, Link is an interface:
> 
> ```go
> type Link interface {
> 	Tag() string
> 	Detail() string
> 	ToOutbound() *conf.OutboundDetourConfig
> }
> ```
> 
> Works for `vmess://` and `vless://` in the future (if it would be there)
> 
> Parsing procedure of `vmess://` links, tries and fallback between different formats. We can add the official format then.

Yes, I personally don't like the format of NG(other)
We are still discussing standards, Are you interested in joining the Telegram Group?

**Comment by qjebbs** [comment]
@kslr Of course. How?

**Comment by qjebbs** [comment]
这个PR目标是添加 `links` 和 `ping` 命令，与官方链接格式有间接关联，但没有直接关联。因此：

- 将链接解析器改为注册机制
- 根据之前讨论，默认不启用第三方链接支持

这样，这个PR可以绕开对官方格式进展的依赖，可以考虑先提交。

> 目前状态下 `links`，`ping` 命令是完成状态，只是没有注册任何链接解析器，因此不能工作。

> 用户可以用反裁剪的方式，开启第三方链接格式支持。

若是认为以下说法成立，请考虑合并此PR：

- `links` 和 `ping` 命令是有必要的
- 链接解析器注册机制可以接受，后续在此基础上添加 `vmess://`,`vless://` 等支持

若否，如一开始所说的，我留作个人用途。

**Comment by Loyalsoldier** [comment]
Why closed?

**Comment by qjebbs** [comment]
> Why closed?

I realized that:
- leastload takes most job of ping for me
- links cmd to fetch subscription, it's kind of not the "core" stuff

**Pull request closed without merging**
