### PR TITLE
perf: RandomStrategy.PickOutbound reuse statusMap

### PR DESCRIPTION
**Pull request by mkmark**
reuse statusMap, should gain some performance boost.

### CODE REVIEW

**Comment by xiaokangwang** [comment]
Hi! Thanks for the pull request.

I was unable to understand what operation you are attempting to reduce:
Is that `s.observatory.GetObservation(s.ctx)` or `common.Must2(s.observatory.(features.TaggedFeatures).GetFeaturesByTag(s.settings.ObserverTag)).(extension.Observatory).GetObservation(s.ctx)` ? they will be executed in with or without this merge request. Assume that is the case, if they are not executed every time, then stall result should be eliminated by maybe have a cache life time setting? 

Are you attempting to reduce map allocation? That was not the most expensive operation here.

Please let me know what kind of operation you are intent to reduce, and we can discuss a plan.

**Comment by mkmark** [comment]
The intent was to merely reduce map allocation, not some great boost but better than nothing...
On the other hand, should any optimization be added to `GetObservation` (via cache or other means), I believe that should be implemented on the observatory side.

**Comment by xiaokangwang** [comment]
I have checked your code, and I was not convinced that reducing a map allocation would make sense when it comes increased code complexity, considering:

1. The shared map is not emptied before each use. Since outbound can be removed and subsequently untracked by the observatory, stalled value must be removed from the cached map structure. 
2.  The shard map is must be guarded with synchronization primitives like memory barrier and even locks, as it could be accessed from more than one threads. This operation would nullify whatever performance gain by avoiding a map allocation.

**Comment by mkmark** [comment]
Oh my... thanks for the suggestions!

**Pull request closed without merging**
