### PR TITLE
improve commands

### PR DESCRIPTION
**Pull request by qjebbs**
This PR:

- format loading improved, see https://github.com/v2fly/v2ray-core/pull/648#issuecomment-781948773
- combines all statistics commands to one
    - make it human readable (use -json for programing-friendly output)
    - multi-patterns support
    - regexp patterns support
- rename `restartlogger` to `api log`, add log following
- add `-json` flag to cmds
- update flags description
    * update flag descriptions
    * change "-v" of "api bo" to duration
    * change "-expire" of "tls cert" to days
- others

```sh
v2ray api stats -runtime # v2ray api statssys
v2ray api stats all.node1 # v2ray api statsget -name "all.node1"
v2ray api stats -json node1 node2 # v2ray api statsquery -name "node1"; v2ray api statsquery -name "node2"
v2ray api stats -regexp 'node1.+downlink' # new
v2ray api log # new, follow logs
v2ray api log --restart # v2ray api restartlogger
```

### Examples

```sh
v2ray api stats -runtime
# 1   Up time               1h49m7s   
# 2   Memory obtained       138.83MB  
# 3   Number of goroutines  222       
# 4   Heap allocated        6.93MB    
# 5   Live objects          84712     
# 6   Heap allocated total  394.39MB  
# 7   Heap allocate count   5287466   
# 8   Heap free count       5202754   
# 9   Number of GC          110       
# 10  Time of GC pause      143.282649ms
v2ray api stats -runtime -json
# {
#   "NumGoroutine": 208,
#   "NumGC": 111,
#   "Alloc": 6615144,
#   "TotalAlloc": 416545216,
#   "Sys": 145575944,
#   "Mallocs": 5321673,
#   "Frees": 5241267,
#   "LiveObjects": 80406,
#   "PauseTotalNs": 143417944,
#   "Uptime": 6613
# }
```

```sh
v2ray api stats node1 node2:
# 1   0           outbound>>>all.node1>>>traffic>>>downlink
# 2   0           outbound>>>all.node1>>>traffic>>>uplink
# 3   68.91MB     outbound>>>all.node2>>>downlink
# 4   1.49MB      outbound>>>all.node2>>>uplink
#
# Total: 70.40MB
v2ray api stats -json node1 node2
# {"stat":[{"name":"outbound>>>all.node1>>>traffic>>>uplink"},{"name":"outbound>>>all.node2>>>traffic>>>uplink","value":1611277},{"name":"outbound>>>all.node2>>>traffic>>>downlink","value":72614836},{"name":"outbound>>>all.node1>>>traffic>>>downlink"}
```

## PS

For other format output:

```sh
v2ray api stats -json node1 node2 | v2ray convert -o=yaml
```

### CODE REVIEW

**Comment by qjebbs** [comment]
The last commit adds `-json` flag to `v2ray api bi`, so that third-party-programs don't have to parse the table, but they still has to parse values, like time, status, which are different between strategies.

**Comment by kslr** [comment]
> rstlogger
 I think vague abbreviations should be avoided

**Comment by qjebbs** [comment]
> > rstlogger
> 
> I think vague abbreviations should be avoided

reverted

**Comment by Loyalsoldier** [comment]
Go v1.16 introduces a new package called `runtime/metrics`. Is it better to use it instead?

ref: https://golang.org/doc/go1.16#runtime

**Comment by qjebbs** [comment]
> Go v1.16 introduces a new package called `runtime/metrics`. Is it better to use it instead?
> 
> ref: https://golang.org/doc/go1.16#runtime

Sorry, homebrew here is still 1.15.8, it's not convenient to try the new package.

**Comment by qjebbs** [comment]
### Improved format loading 

#### For end users:

- auto detect config format
- mixed config formats support
- Improvements above also comes to `api adi, ado, rmi, rmo`

```
Examples:

	{{.Exec}} run -d dir                        (1)
	{{.Exec}} run -c c1.json -c c2.yaml         (2)
	{{.Exec}} run -format=json -d dir           (3)
	{{.Exec}} test -c c1.yml -c c2.pb           (4)
	{{.Exec}} test -format=pb -d dir            (5)
	{{.Exec}} test -format=protobuf -c c1.json  (6)

(1) Load all supported files in the "dir".
(2) JSON and YAML are merged and loaded.
(3) Load all JSON files in the "dir".
(4) Goes error since .pb is not mergeable to others
(5) Works only when single .pb file found, if not, failed due to 
    unmergeable.
(6) Force load "c1.json" as protobuf, no matter its extension.
```

#### For developpers:

* "infra/conf/merge" refactor
* "core.LoadConfig" refactor
* add "infra/conf/mergers"
    * contribute to it will benefit `run`,`test`,`convert`, `api adi, ado, rmi, rmo`
    * easily add new formats, by just adding a converter like json.FromTOML
* default format auto, to all cmds above
    * auto detect input format
    * mixed formats support
* don't use 'stdin:' placeholder
* `v2ray test` now behaves exactly the same with `v2ray run`, including stdin reading

**Comment by kslr** [comment]
Thank you for your work. 
I'm sorry, that I'm not in the best shape, which caused a long delay.

**Pull request merged**
