### PR TITLE
Added Replay Protection for ss proxy

### PR DESCRIPTION
**Pull request by xiaokangwang**
With all the necessary respect, shadowsocket's protocol have issue with replay attack and there is no fix to that regardless how implementation try to migrate that. This is a patch make it a little harder to execute a attack on the protocol for client and servers.

This is does NOT fix any protocol vulnerabilities, and critical unfixed protocol vulnerabilities remains as is, since it is not a implementation imperfection, they are design flaws within the shadowsocket's protocol specification.

### CODE REVIEW

**Comment by database64128** [comment]
IV checker should be considered fundamental in our Shadowsocks implementation. Please consider dropping the option to disable it. It should be enabled by default, just like shadowsocks-rust and go-shadowsocks2.

**Comment by xiaokangwang** [comment]
I think your idea make senses, but i still think adding a option and don't enable it by default and forced right now is NOT the best option.

A options in V2Ray is not only used to indicate the possibility of setting it, it also is a way to express the revision of functions. This will make it possible to reflectively describe the capacities  of a v2ray instance. Also, adding such a options will allow the user to redress any implementation issue of the replay protection.

We could make it default once we have enough confidence on this implementation. But I believe this job is better delegated to the developer of V2Ray clients. If a user can use V2Ray with the json and command line interface, they probably know what they are doing.

**Comment by database64128** [comment]
I disagree. IV filter has been implemented in every well-maintained shadowsocks implementation as a best practice. The feature is intended to be transparent to users. Here at v2ray, we are just fixing this loophole that should've been fixed years ago.

If you insist on keeping the option, I insist we add an option to force disable legacy VMess as well, so we don't have to modify the systemd unit file to add environment variables. (Yes, I saw the discussions in #596)

**Comment by xiaokangwang** [comment]
I agree with adding a option to disable legacy vmess. I think the reason the author decided to use environment variable is that the author do not know how to add a option in vmess.

**Comment by dyhkwong** [comment]
Because you have to append something like `"aeadEnforced": true` for each vmess inbound object if you decide to add an option for vmess instead. Are there any mechanisms in v2ray to override an option for all inbounds except for environment variable?

**Comment by database64128** [comment]
> Because you have to append something like `"aeadEnforced": true` for each vmess inbound object if you decide to add an option for vmess instead.

Just like how we'll have to add `"ivCheck": true` for each and every shadowsocks inbound and outbound object. This is just stupid and I'm against it. But it's @xiaokangwang's decision to make.

**Comment by xiaokangwang** [comment]
> Because you have to append something like `"aeadEnforced": true` for each vmess inbound object if you decide to add an option for vmess instead. Are there any mechanisms in v2ray to override an option for all inbounds except for environment variable?

You can use policy instead, which have a global effect. It is used to set things like connection timeout, but also can be used to set a global setting.

**Comment by xiaokangwang** [comment]
@kslr have instructed me not to incorporate this pr into v4.36.0 release.

**Comment by kslr** [comment]
I think it should be enabled by default, it's not something that's part of the user setting.

**Comment by U-v-U** [comment]
Merge conflict resolved by reverse merging `master` into `dev-ssivfilter`.
To make the git log clean, do we need squash merging?

**Comment by kslr** [comment]
> Merge conflict resolved by reverse merging `master` into `dev-ssivfilter`.
> To make the git log clean, do we need squash merging?

屏幕快照 2021-03-19 下午10 13 26

**Comment by xiaokangwang** [comment]
If @kslr believe this should be enabled for default and there is enough testing, then it will. Please make sure to test this pr so that we could include it.

**Comment by rurirei** [comment]
hello, if the `ivCheck` should be enabled both on the server and client?

**Comment by database64128** [comment]
@rurirei Yes, it should be enabled on both ends.

**Pull request merged**
