### PR TITLE
Do NOT throw error on missing geo lists

### PR DESCRIPTION
**Pull request by Loyalsoldier**
Fixes https://github.com/v2fly/v2ray-core/issues/237

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Now the v2ctl log becomes like this when coming into missing geo lists:

```
V2Ray v4.33.0 (user) 20201215-184216 (go1.15.5 darwin/amd64)
A unified platform for anti-censorship.
2020/12/15 18:50:02 [Info] v2ray.com/core/main/jsonem: Reading config: ./config.json
2020/12/15 18:50:02 [Warning] v2ray.com/core/infra/conf: list not found in geosite.dat: efg
2020/12/15 18:50:02 [Warning] v2ray.com/core/infra/conf: all attributes match no rule: geosite:cn@bb
2020/12/15 18:50:02 [Warning] v2ray.com/core/infra/conf: list not found in geosite.dat: hij
2020/12/15 18:50:03 [Warning] v2ray.com/core/infra/conf: all attributes match no rule: geosite:abc@cn
2020/12/15 18:50:03 [Warning] v2ray.com/core/infra/conf: all attributes match no rule: geosite:cn@aa
```

**Comment by kslr** [comment]
I think it is more appropriate to throw an error

**Comment by U-v-U** [comment]
This should not be a warning, instead, I agree with the current implementation.
It's a basic requirement to verify the correctness that user inputs.

**Comment by Loyalsoldier** [comment]
I want to remove many lists from `geosite.dat` in the future, which will lead to failure start up of V2Ray. To mitigate the influence to end users, we will need to return no error on missing geo lists.

**Comment by U-v-U** [comment]
We should notify users about this breaking change in the geosite file, instead of modifying the code to bypass the validity check.

**Pull request closed without merging**
