### PR TITLE
Fix: app/stats.Manager does not implement features/stats.Manager

### PR DESCRIPTION
**Pull request by Loyalsoldier**
Error occurred in https://github.com/v2fly/geoip/actions/runs/245428313

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
ping @vigilans

**Review by Vigilans — COMMENTED** [review]
`UnregisterCounter` is a method supported in v2ray since https://github.com/v2ray/v2ray-core/pull/2208.

But what's surprising is the code from this PR disappeared in v2fly:
https://github.com/v2fly/v2ray-core/blob/16fe0b03f6d684edd06aadf97ce6904cda7d4bae/features/stats/stats.go#L36-L48

They should be added to v2fly again...also an implementation of `UnregisterChannel` could be added in parallel.

**Comment by Loyalsoldier** [comment]
It's wired. I thought it was your mistake.

**Comment by Vigilans** [comment]
If search `UnregisterCounter` in this repo, no related commits will be returned:
image

It is because https://github.com/v2ray/v2ray-core/pull/2208 gets merged in June in v2ray, after v2fly being developed independently. Normally these PRs should be informed to move to v2fly. Maybe there's some conflicts in https://github.com/v2ray/v2ray-core/pull/2725 and not solved correctly.

**Comment by Loyalsoldier** [comment]
@kslr Please merge into v2ray.

**Comment by Vigilans** [comment]
@Loyalsoldier I was about to open a PR to your fork to add `UnregisterChannel` 😢

**Comment by Loyalsoldier** [comment]
> @Loyalsoldier I was about to open a PR to your fork to add `UnregisterChannel` 😢

Sorry for my impatience. Please file a new PR. 😢

**Pull request merged**
