### PR TITLE
chore fixed

### PR DESCRIPTION
**Pull request by Machtergreifung**

### CODE REVIEW

**Comment by database64128** [comment]
Why did you close #1516? Also I don't see the point of sending these patches to fix typos. Feels like a waste of maintainer's time.

**Comment by Machtergreifung** [comment]
> Why did you close #1516? Also I don't see the point of sending these patches to fix typos. Feels like a waste of maintainer's time.

I closed that in the reason that i thought that you would not let that branch to be merged

**Comment by database64128** [comment]
> I closed that in the reason that i thought that you would not let that branch to be merged

That's simply not how GitHub works.

**Comment by Machtergreifung** [comment]
> > I closed that in the reason that i thought that you would not let that branch to be merged
> 
> That's simply not how GitHub works.

Thank you for your answering.This PR just contains some chore fixed.

**Comment by Machtergreifung** [comment]
move to https://github.com/v2fly/v2ray-core/pull/1535

**Pull request closed without merging**
