### PR TITLE
feat: dns nameserver "expectDomains" mode

### PR DESCRIPTION
**Pull request by rurirei**
this is a preview for dns object with the feature **expectDomains** like expectIPs. this could be a alternative for #864 

i'll make the configuration option in later.

### CODE REVIEW

**Comment by xiaokangwang** [comment]
Sorry I am not good at dns part of V2Ray, what is the difference between what you wants to achieve with `expectDomains` and the existing option `domains`?

**Comment by rurirei** [comment]
@xiaokangwang the current dns provides the only **priority**: the dns query matchs client.domains will meet the high priority to make the request.

this introduces the **expectDomain**: looks like client.expectIPs, the dns query will be requested by the client matchs domain only (if there exists the client to be matched), or the client without "domains" object (the "fallback").

the review may pleased of @Loyalsoldier

**Comment by Loyalsoldier** [comment]
Given the fact that v2ray has introduced `disableFallback` for the whole dns object and `skipFallback` for a single dns server, what's the point of this modification? I can't get it.

**Comment by rurirei** [comment]
@Loyalsoldier 
let me take a example.  
requirement: 8.8.8.8 **only** for noskip.example.domain, 8.8.4.4 for all domains **except** noskip.example.domain.

the priority matching causes the potential for dns leakage.
```jsonc
// failed conf
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "domains": [
          "noskip.example.domain"
        ],
        "skipFallback": true
      },
      {
        "address": "8.8.4.4",
        "skipFallback": true
      }
    ]
  }

// dns leak on 8.8.4.4 for noskip.example.domain
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "domains": [
          "noskip.example.domain"
        ],
        "skipFallback": true
      },
      {
        "address": "8.8.4.4",
        "skipFallback": false
      }
    ]
  }

// 8.8.8.8 for all domains
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "domains": [
          "noskip.example.domain"
        ],
        "skipFallback": false
      },
      {
        "address": "8.8.4.4",
        "skipFallback": true
      }
    ]
  }

// 8.8.8.8 and 8.8.4.4 for all domains
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "domains": [
          "noskip.example.domain"
        ],
        "skipFallback": false
      },
      {
        "address": "8.8.4.4",
        "skipFallback": false
      }
    ]
  }
```

**Comment by Loyalsoldier** [comment]
Why not do this:

```
"dns": {
    "disableFallback": true,
    "server": [
      "8.8.4.4",
      {
        "address": "8.8.8.8",
        "domains": ["noskip.example.domain"]
      }
    ]
}
```

**Comment by rurirei** [comment]
@Loyalsoldier that will uses 8.8.4.4 for all domains, 8.8.8.8 will not used.

**Comment by rurirei** [comment]
@Loyalsoldier thanks. let me take an other example.  
requirement: 8.8.2.2 for example.com, 8.8.8.8 and 8.8.4.4 for all domains except example.com.
```jsonc
// leaks on 8.8.8.8 or 8.8.4.4
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "skipFallback": false
      },
      {
        "address": "8.8.4.4",
        "skipFallback": false
      },
      {
        "address": "8.8.2.2",
        "domains": [ "example.com" ],
        skipFallback: true
      }
    ]
  }

// unused 8.8.8.8
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "skipFallback": true
      },
      {
        "address": "8.8.4.4",
        "skipFallback": false
      },
      {
        "address": "8.8.2.2",
        "domains": [ "example.com" ],
        skipFallback: true
      }
    ]
  }

// unused 8.8.4.4
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "skipFallback": false
      },
      {
        "address": "8.8.4.4",
        "skipFallback": true
      },
      {
        "address": "8.8.2.2",
        "domains": [ "example.com" ],
        skipFallback: true
      }
    ]
  }

// failed conf
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "skipFallback": true
      },
      {
        "address": "8.8.4.4",
        "skipFallback": true
      },
      {
        "address": "8.8.2.2",
        "domains": [ "example.com" ],
        skipFallback: true
      }
    ]
  }
```

**Comment by Loyalsoldier** [comment]
Actually the following config will not fail but use the first DNS `8.8.8.8` for domains except `example.com`, and yeah, the `8.8.4.4` will be useless.

```
// failed conf
  "dns": {
    "server": [
      {
        "address": "8.8.8.8",
        "skipFallback": true
      },
      {
        "address": "8.8.4.4",
        "skipFallback": true
      },
      {
        "address": "8.8.2.2",
        "domains": [ "example.com" ],
        skipFallback: true
      }
    ]
  }
```

I think DNS options in V2Ray are pretty complicated already. If you need DNS load balancer, you should build your own with CoreDNS likewise.

**Comment by rurirei** [comment]
ok, i'll give this up

**Pull request closed without merging**
