### PR TITLE
Breaking change: change package name

### PR DESCRIPTION
**Pull request by Loyalsoldier**
This PR has passed these tests on my local computer:

- go vet ./...
- go fmt ./...
- go test ./...
- go build

```
cd $(go env GOPATH)/src/github.com/v2fly/v2ray-core/main
env CGO_ENABLED=0 go build -o $HOME/v2ray -ldflags "-s -w"

cd $(go env GOPATH)/src/github.com/v2fly/v2ray-core/infra/control/main
env CGO_ENABLED=0 go build -o $HOME/v2ctl -tags confonly -ldflags "-s -w"
```

### CODE REVIEW

**Comment by Loyalsoldier** [comment]
Please review this commit `Tools & Docs: change package name` carefully.

ping @kslr @rprx @xiaokangwang

**Comment by rprx** [comment]
个人建议，包名不必是 `github.com/v2fly/v2ray-core`，直接 `v2ray-core` 更好

不过预计今天发布 v4.27.1，发布后再讨论改包名比较合适

**Comment by Vigilans** [comment]
Since 4.27.4 has been released now, will this changing package name be reviewed first? It will have impact on all subsequent commits. 
I would like to apply the last updated toolchain on my PRs before opening them.

**Comment by Loyalsoldier** [comment]
@Vigilans 
Since this is breaking change, it may be merged in V2Ray v5. So you can open your PRs first.

**Comment by Vigilans** [comment]
Maybe it's linting that should be resolved first...

**Comment by Loyalsoldier** [comment]
> Maybe it's linting that should be resolved first...

That's not a problem if you have run `go vet ./... ` and passed.

**Pull request closed without merging**
