### PR TITLE
Update install-release.sh for new release structure

### LINKED ISSUE #81: Release structure change in 4.27.0 breaks install-release.sh
V2ray 4.27.0 changed the release structure but install-release.sh didn't get revised acccordingly.

It still follows the same release structure pre 4.27.0:
https://github.com/v2fly/v2ray-core/blob/91b4bf8154c208c9a21a8bac89535490833cd1d7/release/install-release.sh#L100

As a result, users are unable to upgrade/install v2ray with install-release.sh on some platforms, particularly various arm platforms. For example I am running v2ray on a Raspberry Pi 3B+ on armv7l.

### PR DESCRIPTION
**Pull request by jiahaoliang**
Attempt to fix #81 

I don't have any armv5, armv6, riscv64 setups to test with. So I am not sure what 'uname -m' actually returns on those platforms.

### CODE REVIEW

**Comment by IceCodeNew** [comment]
BTW 我们是不是应该考虑修改 `https://install.direct/go.sh` 指向 fhs 的安装脚本了。
旧的安装脚本应该逐步替换掉，其中第一件事就是让新调用 `https://install.direct/go.sh` 的用户受到警示，表明这个文件的内容即将与 fhs 安装脚本同步，然后过段时间再真的把 fhs 安装脚本同步过来。

现在这样新旧脚本都得维护，不是特别好，要尽快合二为一。

**Comment by jiahaoliang** [comment]
@IceCodeNew @dctxmei Feel free to edit this patch or even summit new PR with changes the team prefers. I am neither a v2ray nor a bash expert whatsoever.

The script is currently in a broken state and there was supposed to be a hotfix for this. I am assuming that is affecting lots of users as majority of them rely on [https://install.direct/go.sh](https://install.direct/go.sh) to install or upgrade v2ray.

Not to mention the issue I posted as #82 . I believe the use of awk -e is incorrect there which makes the script fails on any system that not taking gawk as the default awk utility.

**Comment by kslr** [comment]
I recommend deprecating now

**Comment by dctxmei** [comment]
Should indeed be deprecated immediately.

**Comment by kslr** [comment]
i remove it now

**Pull request closed without merging**
